### ISSUE TITLE
DatePicker Not Working in inertiajs

### ISSUE THREAD

**Issue by eskiesirius** [mdbootstrap/TW-Elements#1026]
Hello.. I tried to install tw-elements through npm and yet date picker isn't working.. im using inertiajs of laravel

```
const defaultTheme = require('tailwindcss/defaultTheme');
const colors = require('tailwindcss/colors');

module.exports = {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './vendor/laravel/jetstream/**/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.vue',
        './node_modules/tw-elements/dist/js/**/*.js'
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Nunito', ...defaultTheme.fontFamily.sans],
            },
            colors: {
                cyan: colors.cyan,
            }
        },
    },

    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/typography'),
        require('@tailwindcss/line-clamp'),
        require('tw-elements/dist/plugin')
    ],
};
```

**Comment by Trochonovitz** [comment]
Include import from Vite in your `welcome/app.blade.php` file: `@vite('resources/js/app.js')`. FYI in next week we are going to publish some tutorials about integration Tailwind Elements with popularn front and backend frameworks.

**Comment by Trochonovitz** [comment]
Hi, we just have launched bunch of integration tutorials - both with CSR and SSR frameworks. If you have more questions about integration or you still got some problems with particular components, let us know by adding [new issue](https://github.com/mdbootstrap/Tailwind-Elements/issues) / topic in [discussions section](https://github.com/mdbootstrap/Tailwind-Elements/discussions) (if there are some unclear informations or just want let us know about something).

[Laravel integration tutorial](https://tailwind-elements.com/docs/standard/integrations/laravel-integration/).
