### ISSUE TITLE
in laravel i am getting this issue path not found

### ISSUE THREAD

**Issue by Elusoji** [mdbootstrap/TW-Elements#1028]
T http://127.0.0.1:8000/TW-ELEMENTS-PATH/dist/js/index.min.js net::ERR_ABORTED 404 (Not Found)

**Comment by discern** [comment]
In your `resources/js/app.js` file, add `import 'tw-elements';`. Then, stop and restart `npm run watch`. If you do it this way, you won't need to include the script tag mentioned above in your HTML, as it will be included in the main app's javascript.

**Comment by Trochonovitz** [comment]
Adding to @discern answer: include import from vite in your `welcome.blade.php` file: `@vite('resources/js/app.js')`. FYI in next week we are going to publish some tutorials about integration Tailwind Elements with popularn front and backend frameworks.

In case you want to import library by script tags: phrase "TW-ELEMENTS-PATH" is just placeholder; you got to rename it to real path where Tailwind Elements is installed.

**Comment by Trochonovitz** [comment]
Hi, we just have launched bunch of integration tutorials - both with CSR and SSR frameworks. If you have more questions about integration or you still got some problems with particular components, let us know by adding [new issue](https://github.com/mdbootstrap/Tailwind-Elements/issues) / topic in [discussions section](https://github.com/mdbootstrap/Tailwind-Elements/discussions) (if there are some unclear informations or just want let us know about something).

[Laravel integration tutorial](https://tailwind-elements.com/docs/standard/integrations/laravel-integration/).

**Comment by ATahhan** [comment]
> Hi, we just have launched bunch of integration tutorials - both with CSR and SSR frameworks. If you have more questions about integration or you still got some problems with particular components, let us know by adding [new issue](https://github.com/mdbootstrap/Tailwind-Elements/issues) / topic in [discussions section](https://github.com/mdbootstrap/Tailwind-Elements/discussions) (if there are some unclear informations or just want let us know about something).
> 
> [Laravel integration tutorial](https://tailwind-elements.com/docs/standard/integrations/laravel-integration/).

It doesn't seem like the Laravel tutorial link is working, I'm just seeing the home page of https://tailwind-elements.com in https://tailwind-elements.com/docs/standard/integrations/laravel-integration/

**Comment by f1rf1n** [comment]
> It doesn't seem like the Laravel tutorial link is working, 

It is working now? IF it still isn't for you maybe try another browser or something?

**Comment by Trochonovitz** [comment]
Yes, all tutorials are back live. It was our mistake.
