### ISSUE TITLE
align right dropdown menu

### ISSUE THREAD

**Issue by ericamigo** [mdbootstrap/TW-Elements#1032]
can't find in the docs the support for this. js is using inset and not possible to override using `right-0`

**Comment by smolenski-mikolaj** [comment]
Please check this section: https://tailwind-elements.com/docs/standard/components/dropdown/#dropright

**Comment by 1isten** [comment]
But how to align right in drop**down**?

<img width="559" alt="image" src="https://user-images.githubusercontent.com/11518941/218772759-e47b0a41-aa1c-443c-a9df-aff72f38be3e.png">
