### ISSUE TITLE
Missing instruction about CSS

### ISSUE THREAD

**Issue by Victoria91** [mdbootstrap/TW-Elements#1033]
Hello, thanks for the library!
I've followed your instructions from [here](https://tailwind-elements.com/quick-start/), but could not get the date picker to work. As I've inspected, it requires some specific CSS, so could you specify the correct way to include all necessary styles?

Thanks

**Comment by ferezoz** [comment]
@emorevival It works thank you but here is a better way of doing it:
```js
import dynamic from 'next/dynamic';

dynamic(() => import('tw-elements'), {
  ssr: false
});
```

**Comment by ahmetskilinc** [comment]
@emorevival Where did you put this `useEffect`?

**Comment by emorevival** [comment]
@ahmetskilinc If memory serves me well I put it in my `index.tsx`

**Comment by wilychris** [comment]
after a year, i still need help.. 
following the [official guide](https://tailwind-elements.com/docs/standard/getting-started/quick-start/), stuck on point 4. i don't get where TW-ELEMENTS-PATH should point to.
i'm on:
- react 18 ( without next.js nor vite )
- tailwind 3.2.7
- jsx

installed using npm, folder tw-elements is in 'node_modules' directory. so how do i point to that directory? i thought only 'src' is callable.

**Comment by Trochonovitz** [comment]
@wilychris `./node-modules/tw-elements/dist/js/index.min.js`. Alternatively you can import library by calling import in useEffect hook in App.jsx.

```
  useEffect(() => {
    const use = async () => {
      await import("tw-elements");
    };
    use();
  }, []);
```

**Comment by wilychris** [comment]
> @wilychris `./node-modules/tw-elements/dist/js/index.min.js`. Alternatively you can import library by calling import in useEffect hook in App.jsx.
> 
> ```
>   useEffect(() => {
>     const use = async () => {
>       await import("tw-elements");
>     };
>     use();
>   }, []);
> ```

`useEffect` in App.jsx confirmed, tested, and works on windows chrome 109 and firefox 110.
many thanks @Trochonovitz

**Comment by Trochonovitz** [comment]
Hi, we just have launched bunch of integration tutorials - both with CSR and SSR frameworks. If you have more questions about integration or you still got some problems with particular components, let us know by adding [new issue](https://github.com/mdbootstrap/Tailwind-Elements/issues) / topic in [discussions section](https://github.com/mdbootstrap/Tailwind-Elements/discussions) (if there are some unclear informations or just want let us know about something).

[Next.js integration tutorial](https://tailwind-elements.com/docs/standard/integrations/next-integration/).
