### ISSUE TITLE
Reinitialize Datepicker after it was placed in the DOM via AJAX

### ISSUE THREAD

**Issue by np-tt** [mdbootstrap/TW-Elements#1036]
How can I reinitialize the datepicker after a corresponding input field has been placed in the DOM via Ajax? Unfortunately I can't find any instructions or JS documentation.

**Comment by michaelnera** [comment]
Did you find any solution to this? This is also our problem.

**Comment by smolenski-mikolaj** [comment]
We're going to refactor the library soon. According to [this](https://github.com/mdbootstrap/Tailwind-Elements/issues/1125) and [this](https://github.com/mdbootstrap/Tailwind-Elements/issues/1105) tasks, there will be such option available and described in the docs.
