### ISSUE TITLE
nextjs error - ReferenceError: document is not defined error

### ISSUE THREAD

**Issue by hanumanjiblog** [mdbootstrap/TW-Elements#1044]
nextjs error - ReferenceError: document is not defined error, please fix this bug

**Comment by hostedposted** [comment]
You need to dynamically load it.
Try something like this:
```js
import dynamic from "next/dynamic"
dynamic(() => import("tw-elements"), { ssr: false })
```

**Comment by Chetan-B-B** [comment]
Thanks for mentioning the solution :)

**Comment by Chetan-B-B** [comment]
This works
***
const {} = dynamic(import("tw-elements"), { ssr: false }); 
***

**Comment by SirArchibald97** [comment]
I had this issue and the above solution worked however the element I was using then stopped working? 

I am using the accordion example found at the top of [this](https://tailwind-elements.com/docs/standard/components/accordion/) page.

**Comment by Heldeenn** [comment]
> I had this issue and the above solution worked however the element I was using then stopped working?
> 
> I am using the accordion example found at the top of [this](https://tailwind-elements.com/docs/standard/components/accordion/) page.

I'm using "require" instead of "import" and it works just fine. I don't understand why though.
```javascript
import dynamic from "next/dynamic";
dynamic(require("tw-elements"), { ssr: false });
```

**Comment by hex-grammer** [comment]
> This works
> 
> const {} = dynamic(import("tw-elements"), { ssr: false });

I almost giveup using tw-elements until i got your comment.
Thankyou so much🤩👍🏻

**Comment by Trochonovitz** [comment]
Hi, we just have launched bunch of integration tutorials - both with CSR and SSR frameworks. If you have more questions about integration or you still got some problems with particular components, let us know by adding [new issue](https://github.com/mdbootstrap/Tailwind-Elements/issues) / topic in [discussions section](https://github.com/mdbootstrap/Tailwind-Elements/discussions) (if there are some unclear informations or just want let us know about something).

[Next.js integration tutorial](https://tailwind-elements.com/docs/standard/integrations/next-integration/).

**Comment by SMSDev1** [comment]
I still get this error. I've been through the Next.js integration tutorial and its not massively helpful. I don't think the _app.js file is made by default. Even with the above I get "initTE' is not exported from tw-elements. I find that the tw-elements.d.ts file just contains 'declare module "tw-elements' which is a bit odd to me?

Just created a new project to follow the Next.js integration tutorial and I get the same errors
Attempted import error: 'Datepicker' is not exported from 'tw-elements' (imported as 'Datepicker').

@Trochonovitz
