### ISSUE TITLE
Dynamic require of "tw-elements/dist/plugin" is not supported

### ISSUE THREAD

**Issue by sysmat** [mdbootstrap/TW-Elements#1046]
- package.json
```json
"devDependencies": {
    "@sveltejs/vite-plugin-svelte": "^1.0.0-next.30",
    "@tsconfig/svelte": "^2.0.1",
    "autoprefixer": "^10.4.7",
    "postcss": "^8.4.13",
    "sass": "^1.51.0",
    "svelte": "^3.44.0",
    "svelte-check": "^2.2.7",
    "svelte-preprocess": "^4.9.8",
    "tailwindcss": "^3.0.24",
    "tslib": "^2.3.1",
    "typescript": "^4.5.4",
    "vite": "^2.9.7"
  },
  "dependencies": {
    "tw-elements": "^1.0.0-alpha12"
  }
```
- tailwind.config.cjs
```js
module.exports = {
  content: [
    './index.html',
    './src/**/*.{svelte,js,ts}'
  ],
  theme: {
    extend: {},
  },
  plugins: [require('tw-elements/dist/plugin')],
};

```
- Error: **Dynamic require of "tw-elements/dist/plugin" is not supported**

**Comment by jerrypena1** [comment]
I'm having a similar issue with NuxtJS 3

- package.json

```js
 "devDependencies": {
    "nuxt": "3.0.0-rc.1"
  },
  "dependencies": {
    "tw-elements": "^1.0.0-alpha12"
  }
```

- tailwind.config.js

```js
module.exports = {
  content: ['./**/*.{html,js,vue}', './node_modules/tw-elements/dist/js/**/*.js'],
  plugins: [require('tw-elements/dist/plugin.js')],
}
```

- Error

Uncaught SyntaxError: The requested module '/_nuxt/plugins/tw-elements.js' does not provide an export named 'default' (at client.mjs:5:8)

**Comment by carlos-dubon** [comment]
```svelte
<script lang="ts">
  import { onMount } from "svelte";
  import "../styles/globals.css";

  // import tw-elements with no SSR
  onMount(async () => {
    await import("tw-elements");
  });
</script>

<slot />

```

```cjs
module.exports = {
  content: [
    "./src/**/*.{html,js,svelte,ts}",
    "./node_modules/tw-elements/dist/js/**/*.js",
  ],
  theme: {
    extend: {},
  },
  plugins: [require("tw-elements/dist/plugin")],
};

```

this worked for me on svelte-kit

**Comment by domgom** [comment]
@carlos-dubon could you try to see if the timepicker works? I get the datepicker working but not the timepicker with your config.

**Comment by domgom** [comment]
@carlos-dubon  about datepicker, does your it stop working for you when switching between prefetched svelte tabs? It only works for me on hard manual browser refresh, not coming from another route 😞

**Comment by Trochonovitz** [comment]
Hi, Tailwind Elements in the newewst version (beta1 released a two weeks ago) works fine with Svelte - you got to import library in lifecycle method like @carlos-dubon showed. Timepicker on the other hand is not working indeed but this is our problem which was already solved. Proper fix will be released with beta2.

FYI in a couple of days we are going to publish bunch of tutorials how to integrate TE with most popular CSR and SSR frameworks.

**Comment by Trochonovitz** [comment]
Hi, we just have launched bunch of integration tutorials - both with CSR and SSR frameworks. If you have more questions about integration or you still got some problems with particular components, let us know by adding [new issue](https://github.com/mdbootstrap/Tailwind-Elements/issues) / topic in [discussions section](https://github.com/mdbootstrap/Tailwind-Elements/discussions) (if there are some unclear informations or just want let us know about something).
