### ISSUE TITLE
Cannot read properties of undefined (reading 'getBoundingClientRect') in NextJS

### ISSUE THREAD

**Issue by filipedfs** [mdbootstrap/TW-Elements#1049]
I'm using NextJS and I put a dropdown button on a menu. When I run the app using `yarn dev`, everything works fine. But if I build the app and run using `yarn start` this error appears and the position of the dropdown is wrong.

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getBoundingClientRect')
```

![image](https://user-images.githubusercontent.com/13025635/172017541-416aa374-a9c1-49f7-9351-61b36fc9ae39.png)

![image](https://user-images.githubusercontent.com/13025635/172017560-8d79ffe4-8b36-4db8-acb0-6391867e57b1.png)

**Comment by Trochonovitz** [comment]
Hi, in this case we recommend using CDN.
