### ISSUE TITLE
Model popup cannot initialize.

### ISSUE THREAD

**Issue by ruban-s** [mdbootstrap/TW-Elements#1055]
The Model Popup has issue that produce error onclick model:
The console log Error:
`Uncaught TypeError: this._element is undefined
    value modal.js:312
    value modal.js:194
    o modal.js:83
    value base-component.js:53
    Io modal.js:429
    t event-handler.js:119
    gt event-handler.js:215
    on event-handler.js:249
    <anonymous> modal.js:403
    Webpack 3
modal.js:312:4
`

**Comment by smolenski-mikolaj** [comment]
Modal component is going to be refactored soon, so the issue should be solved.
