### ISSUE TITLE
Trigger Modal using JS

### ISSUE THREAD

**Issue by Aniruddh-J** [mdbootstrap/TW-Elements#1056]
Hello,

Thanks for the wonderful library. I was going through the documentation but I couldn't find any way to trigger the modal with JS.

I have a project coming in where the front-end will be in Vue3. Is there any way I can achieve it?

**Comment by Aniruddh-J** [comment]
Maybe make a hidden button and trigger a click event on the button?

**Comment by ArturHorbenko** [comment]
+1

**Comment by smolenski-mikolaj** [comment]
Connected with the global library name issue: https://github.com/mdbootstrap/Tailwind-Elements/issues/1125
Will be available soon.

**Comment by kespaldon** [comment]
You can actually do some javascript trikery with this.

```js
const backdrop = document.getElementsByClassName("modal-backdrop")[0];
backdrop.classList.add("show");

const modal = document.getElementById("myModal");
modal.classList.add("show");
```

worked for me. hope it does for you too.
