### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by ElbinBinil** [mdbootstrap/TW-Elements#1058]
In next js when I try to import tw-elements the app is getting crashed and giving an message "ReferenceError: document is not defined"
![image](https://user-images.githubusercontent.com/41504088/175249724-03a2b07e-3c43-42a6-87f3-fc0e7c33d3f8.png)

**Comment by beeb** [comment]
Same here, I am assuming it's because of server-side rendering?

EDIT: duplicate of https://github.com/mdbootstrap/Tailwind-Elements/issues/1038 which is still unsolved since January

**Comment by busychild** [comment]
+1

**Comment by Taarek** [comment]
What you can do in the meantime is drag the ``index.min.js`` (found in ``/node_modules/tw-elements/dist/js/``) into your static folder, then use this inside a custom layout (https://nextjs.org/docs/basic-features/layouts).
 I personally put it inside a parent div, before the ``<main>{children}</main>``
```tsx
<Script src="index.min.js"/>
```

Although, I do not know if this is bad practice or not. The only thing I can think of is that you'll need to update the index.min.js inside your static folder yourself whenever it gets updated upstream.

**Comment by slamer59** [comment]
@Taarek this way we can have SSR ?

**Comment by Adonis0123** [comment]
This is how I solved it

/_app.tsx

```
function MyApp({ Component, pageProps }: AppProps) {
  useEffect(() => {
    const use = async () => {
      (await import('tw-elements')).default;
    };
    use();
  }, []);

  return <Component {...pageProps} />;
}

export default MyApp;
```

**Comment by Taarek** [comment]
> @Taarek this way we can have SSR ?

I'm not sure how to see that. I'm pretty new to the whole nextjs/react world. 

I haven't ran into any issues at least from what I can tell.

**Comment by uricantasala** [comment]
> +1

+1 

I'll try what is suggested

**Comment by uricantasala** [comment]
> This is how I solved it
> 
> /_app.tsx
> 
> ```
> function MyApp({ Component, pageProps }: AppProps) {
>   useEffect(() => {
>     const use = async () => {
>       (await import('tw-elements')).default;
>     };
>     use();
>   }, []);
> 
>   return <Component {...pageProps} />;
> }
> 
> export default MyApp;
> ```

It worked like a charm.

Many thanks!

Really appreciated!!

It saved me more time spending on this.

😊 ❤️

**Comment by locohost** [comment]
> This is how I solved it
> 
> /_app.tsx
> 
> ```
> function MyApp({ Component, pageProps }: AppProps) {
>   useEffect(() => {
>     const use = async () => {
>       (await import('tw-elements')).default;
>     };
>     use();
>   }, []);
> 
>   return <Component {...pageProps} />;
> }
> 
> export default MyApp;
> ```

Yeah this works. This needs to be in the official documentation somewhere.

**Comment by devSahinur** [comment]
> This is how I solved it
> 
> /_app.tsx
> 
> ```
> function MyApp({ Component, pageProps }: AppProps) {
>   useEffect(() => {
>     const use = async () => {
>       (await import('tw-elements')).default;
>     };
>     use();
>   }, []);
> 
>   return <Component {...pageProps} />;
> }
> 
> export default MyApp;
> ```

thanks you so much dude @Adonis0123

**Comment by andrei-ivanov** [comment]
Duplicate of #1044
@filipkappa @marveluck Any chance for a fix pretty please?
People are have started to resort to some very ridiculous [workarounds](https://stackoverflow.com/questions/71875270/how-to-install-the-tailwind-elements-in-nextjs#answer-72250961) for this issue.

**Comment by eafelix** [comment]
Hi Guys, for the `nextjs` users you only need to create the `_document.js` file with the next `<Script/>` component

```
import { Html, Head, Main, NextScript } from 'next/document'
import Script from 'next/script'

// import 'tw-elements';

export default function Document() {
  return (
    <Html>
      <Head />
      <body>
        <Main />
        <NextScript />
        <Script src="./TW-ELEMENTS-PATH/dist/js/index.min.js"/>
      </body>
    </Html>
  )
}
```

**Comment by bllfoad** [comment]
tried every thing the same problem

**Comment by ensarince** [comment]
finally solved the issue.

 I added 

```
  import dynamic from "next/dynamic"
  const {} = dynamic(import("tw-elements"), { ssr: false });
```

to the _index.tsx_ file
which caused another error when deploying the website.
I solved that also by adding _index.d.ts_ file to root
inside that file, I added

`declare module "tw-elements"`

line and also added **"index.d.ts"** to the include in _tsconfig.json_ file

**Comment by svandegar** [comment]
> useEffect(() => {
>     const use = async () => {
>       (await import('tw-elements')).default;
>     };
>     use();
>   }, []);

Worked perfectly! Thank you!

**Comment by juvenalBOBENZE** [comment]
**moi j'ai essayé toutes ces methodes mais ça ne marche toujours pas, je fais du nextt js**

function MyApp({ Component, pageProps }: AppProps) {
 ~~useEffect~~ (() => {
    const use = async () => {
      (await import('~~tw-elements~~')).default;
    };
    use();
  }, []);

  return <Component {...pageProps} />;
}

export default MyApp;


le code est souligné

**Comment by izzie91** [comment]
Please, about this issue, i can not get my component to see the script js file, so it's not working properly any tw-elements component I  am trying to use.
I did: in tailwind.config.js
 content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./src/**/*.{html,js}",
    "./node_modules/tw-elements/dist/js/**/*.js",
    "./node_modules/react-tailwindcss-datepicker/dist/index.esm.js",
  ],
plugins: [require("tw-elements/dist/plugin"), require("@tailwindcss/forms")],

////

in _app.js i did:

useEffect(() => {
    const use = async () => {
      ;(await import("tw-elements")).default
    }
    use()
  }, []) 

////
and finally i try to use some of the codein tw-elemts but they are not working

what am i doing wrong?

**Comment by VictorSS** [comment]
Tried everthing above, still no success, considering i'm using Next 13. Pls if someone find a better solution pls help.

**Comment by Trochonovitz** [comment]
Hi, we just have launched bunch of integration tutorials - both with CSR and SSR frameworks. If you have more questions about integration or you still got some problems with particular components, let us know by adding [new issue](https://github.com/mdbootstrap/Tailwind-Elements/issues) / topic in [discussions section](https://github.com/mdbootstrap/Tailwind-Elements/discussions) (if there are some unclrear informations or just want let us know about something).

[Next.js integration tutorial](https://tailwind-elements.com/docs/standard/integrations/next-integration/).

**Comment by stevebrowndotco** [comment]
@Trochonovitz link is broken btw

**Comment by rain84** [comment]
Hey, guys!
This is my approach with a **NextJS 13** and new **AppRouter**.

1. Create component for the initialisation of TWElements

```
"use client";
import { useEffect } from 'react';

export const TWElementsInit = () => {
  useEffect(() => {
    ;(async () => (await import('tw-elements')))()
  }, []);
  return null
}
```

2. Import into ```app/layout.tsx``` (which replaced the old one '_app.tsx')
```
import './globals.css'
import {TWElementsInit} from './tw'

export const metadata = {
  title: 'Title,
  description: 'description,
}

export default function RootLayout({
  children,
}: {   children: React.ReactNode
  }) {
  return (
    <html lang="en">
      <TWElementsInit/>
      <body>{children}</body>
    </html>
  )
}
```

Good luck! :)

**Comment by vforvasquez** [comment]
> Hi, we just have launched bunch of integration tutorials - both with CSR and SSR frameworks. If you have more questions about integration or you still got some problems with particular components, let us know by adding [new issue](https://github.com/mdbootstrap/Tailwind-Elements/issues) / topic in [discussions section](https://github.com/mdbootstrap/Tailwind-Elements/discussions) (if there are some unclrear informations or just want let us know about something).
> 
> [Next.js integration tutorial](https://tailwind-elements.com/docs/standard/integrations/next-integration/).

@Trochonovitz 
The tutorial steps do not work. The components load but do not function. Also using `import`  with `dynamic` gave a type error.

```Argument of type '() => Promise<typeof import("/.../pages/component.ts")>' is not assignable to parameter of type 'DynamicOptions<{}> | Loader<{}>'.
  Type '() => Promise<typeof import("/.../pages/component.ts")>' is not assignable to type '() => LoaderComponent<{}>'.
    Type 'Promise<typeof import("/.../pages/component.ts")>' is not assignable to type 'LoaderComponent<{}>'.
      Type 'typeof import("/.../pages/component.ts")' is not assignable to type 'ComponentType<{}> | ComponentModule<{}>'.ts(2345)
      ```

**Comment by Trochonovitz** [comment]
@vforvasquez change your file extension to `.tsx` instead of `.ts`.

**Comment by carlosriveroib** [comment]
> Hey, guys! This is my approach with a **NextJS 13** and new **AppRouter**.
> 
> 1. Create component for the initialisation of TWElements
> 
> ```
> "use client";
> import { useEffect } from 'react';
> 
> export const TWElementsInit = () => {
>   useEffect(() => {
>     ;(async () => (await import('tw-elements')))()
>   }, []);
>   return null
> }
> ```
> 
> 2. Import into `app/layout.tsx` (which replaced the old one '_app.tsx')
> 
> ```
> import './globals.css'
> import {TWElementsInit} from './tw'
> 
> export const metadata = {
>   title: 'Title,
>   description: 'description,
> }
> 
> export default function RootLayout({
>   children,
> }: {   children: React.ReactNode
>   }) {
>   return (
>     <html lang="en">
>       <TWElementsInit/>
>       <body>{children}</body>
>     </html>
>   )
> }
> ```
> 
> Good luck! :)

and how do you init Carousel for example?

**Comment by JustARatherRidiculouslyLongUsername** [comment]
> > Hey, guys! This is my approach with a **NextJS 13** and new **AppRouter**.
> > 
> > 1. Create component for the initialisation of TWElements
> > 
> > ```
> > "use client";
> > import { useEffect } from 'react';
> > 
> > export const TWElementsInit = () => {
> >   useEffect(() => {
> >     ;(async () => (await import('tw-elements')))()
> >   }, []);
> >   return null
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. Import into `app/layout.tsx` (which replaced the old one '_app.tsx')
> > 
> > ```
> > import './globals.css'
> > import {TWElementsInit} from './tw'
> > 
> > export const metadata = {
> >   title: 'Title,
> >   description: 'description,
> > }
> > 
> > export default function RootLayout({
> >   children,
> > }: {   children: React.ReactNode
> >   }) {
> >   return (
> >     <html lang="en">
> >       <TWElementsInit/>
> >       <body>{children}</body>
> >     </html>
> >   )
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Good luck! :)
> 
> and how do you init Carousel for example?

Like so
```tsx
export const TWElementsInit = () => {
  useEffect(() => {
    (async () => {
      const { initTE, Carousel } = await import('tw-elements');
      initTE({ Carousel });
    })();
  }, []);
  return null;
};
```

**Comment by AliAbdllah** [comment]
Tried everything and nothing worked except for adding this code for every component I'm creating:

```
"use client";
import { useEffect } from "react";
const AppSelect = () => {
    useEffect(() => {
        const init = async () => {
            const { Select, initTE } = await import("tw-elements");
            initTE({ Select });
        };
        init();
    }, []);
    return (
        <>
            <select data-te-select-init multiple>
                <option value="1">One</option>
                <option value="2">Two</option>
                <option value="3">Three</option>
                <option value="4">Four</option>
                <option value="5">Five</option>
                <option value="6">Six</option>
                <option value="7">Seven</option>
                <option value="8">Eight</option>
            </select>
            <label data-te-select-label-ref>Example label</label>

        </>
    );
};

export default AppSelect;
```

**Comment by paul-minniti** [comment]
Does anyone have a solution to this using SvelteKit??

**Comment by IliaNikonorov** [comment]
@ignitehub-dev I've just run into this issue today in my SvelteKit project. Kudos to the guys above, a SvelteKit alternative to their NextJS code seems to work:

```
<script context="module">
  import { onMount } from 'svelte'; // import onMount either here or in the next script
  export function initTWE() {
    onMount(async () => {
      const { initTE, Select } = await import('tw-elements');
      initTE({ Select });
    });
  }
</script>
```

and then

```
<script>
initTWE()
</script>
```


Not sure if it's stable but at least it stopped raising VITE SSR error.

Disclaimer: I'm not even a dev, just a PM learning some JS with Svelte :)

**Comment by paul-minniti** [comment]
@IliaNikonorov i gave up on using TW-Elements as a js package. I found it not to interact nicely when trying to link actions between components with svelteKit. I migrated my project to use [Skeleton](https://github.com/skeletonlabs/skeleton).
