### ISSUE TITLE
deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1

### ISSUE THREAD

**Issue by shokanshi** [mdbootstrap/TW-Elements#1059]
I am getting the above warning with TW-Elements. Apparently popper.js@1.16.1 is still part of the dependencies.

However, within the dependencies, @popperjs/core can be found in it too. 

Does it mean popper.js@1.16.1 can be removed from the dependencies list?

**Comment by sysmat** [comment]
- "tw-elements": "^1.0.0-alpha13", is still using popper.js@1.16.1

```sh
❯ npm list popper.js
svelte_vite@0.0.1 .\svelte_vite
└─┬ tw-elements@1.0.0-alpha13
  └── popper.js@1.16.1
```
