### ISSUE TITLE
Example for CSS Tabs has wrong code

### ISSUE THREAD

**Issue by Baerbeisser** [mdbootstrap/TW-Elements#1061]
The example code in https://tailwind-elements.com/docs/standard/navigation/tabs/#buttons contains no _buttons_ but _a href_ links.
I think it's the code of the basic example?

**Comment by smolenski-mikolaj** [comment]
It's necessary in this case.

**Comment by Baerbeisser** [comment]
Then the title is wrong, because it has no buttons.
