### ISSUE TITLE
Accordion styling doesn't kick in until interactions and sometimes reverts back to default

### ISSUE THREAD

**Issue by mikesol** [mdbootstrap/TW-Elements#1063]
https://user-images.githubusercontent.com/525350/180738284-21ce1572-d9b9-4a4f-bb91-d0f401e037bb.mp4

I'm trying our `tw-elements@1.0.0-alpha12` (really nice work to the team!) and my accordion element functions correctly but the styling is a bit off. Specifically, the styling does not kick in until there's an interaction with the component, and occasionally, it reverts back to the default styling after an interaction.

Looking at the Chrome inspector, it seems as if the correct tailwind classes are there all the time. I'm not using the aria labels currently - could that be causing the bug? Anyway, I thought it would be useful to report it. Thanks!

**Comment by mikesol** [comment]
Digging a bit further, it seems that the `:not(.collapsed)` style reverts to the default styling. Is there any way to theme this? Thanks
<img width="1374" alt="not-collapsed" src="https://user-images.githubusercontent.com/525350/180740772-0d05a69f-f971-48e7-a006-bf5a5ba40a70.png">
!

**Comment by smolenski-mikolaj** [comment]
We're now refactoring the accordion component completely to remove custom classes and move all classes to tailwind, so the issues should be solved in the next release.
