### ISSUE TITLE
Tailwind Elements and Angular

### ISSUE THREAD

**Issue by damienpuaud** [mdbootstrap/TW-Elements#1066]
## Issue
Hi everybody!  
I tried to add Tailwind Elements to my Angular project to be able to use some of your components (eg: Date picker).

Unfortunately, it doesn't seem to work. I have some elements working (like the date picker field is transformed to a kinda material looking floating input). But when I click on it, my **date picker calendar isn't fired**.

I followed the steps given in the NPM [installation guide][1] :  
1- I have Node installed and TailwindCss in my project  
2- Installed Tailwind Elements via npm :
```
npm install tw-elements
```

3-  Added that code in my tailwind.config.ts file :
```javascript
module.exports = {
  content: ['./src/**/*.{html,js}', './node_modules/tw-elements/dist/js/**/*.js'],
  plugins: [
    require('tw-elements/dist/plugin')
  ]
}
```

4- I'm **kinda stuck on point 4 though**... They ask to add in the index.html file this script call :
```javascript
<script src="./TW-ELEMENTS-PATH/dist/js/index.min.js"></script>
```

## What I tried
1- Add that javascript script code (the above one)... But I can't really do that in an Angular project (I tried but it doesn't work).  
2- I tried as well to add this index.min.js file in my project and declare it in my angular.json file on the "scripts" section (doesn't work either).  
3- I tried as well to call this script via a CDN (doesn't work).

So if someone has an idea to make Tailwind Elements work in an Angular project, I'll take any hint ;)

  [1]: https://tailwind-elements.com/quick-start/

**Comment by damienpuaud** [comment]
In fact the problem didn't really come from my install. I tried other components and it seems to work fine.

This freaking DatePicker refuses to get triggered though... Which seems to be a pretty recurrent problem among issues posted on this GitHub.  
But if anyone has an idea about how to make it work... I'l take it ;)

**Comment by Saintenr** [comment]
Hi, 
i've the same problem with react. The DatePicker is not working :(
did you get it working?

**Comment by damienpuaud** [comment]
> Hi, 
> 
> i've the same problem with react. The DatePicker is not working :(
> 
> did you get it working?

Well, not really... But I found a post where a guy rebuilt it in angular to make it work.
Not ideal, I would have preferred a tailwinds elements native way, but hey...
Here's the link to this blog post :
[https://dev.to/timsar2/create-datepicker-by-tailwindcss-angular-3p8k](https://dev.to/timsar2/create-datepicker-by-tailwindcss-angular-3p8k)

**Comment by Esanic** [comment]
I can chime in and say that I can confirm that the datepicker in tw-elements isn't working in Angular (v15.0.3). 
I am glad that I found this post after a couple of hours of tweaking and pulling my hair out.
Hope it'll get sorted out soon.

**Comment by hiddenkirby** [comment]
> https://dev.to/timsar2/create-datepicker-by-tailwindcss-angular-3p8k

Downside to that example is if you need to pick a year.  :(. but kudos to that person for a working tailwind + angular datepicker from scratch. 

Yes, I too, cannot get the tw-elements datepicker to trigger in my angular v15 app.

**Comment by Trochonovitz** [comment]
Hi, unfortunately Tailwind Elements does not working properly with Angular but we do have plans for creating standalone Tailwind Elements Angular library. Without specific date yet.
