### ISSUE TITLE
Hover on mega menu items

### ISSUE THREAD

**Issue by BDZK** [mdbootstrap/TW-Elements#1073]
Hi,

Congrats for this awesome library. Very useful. I have an issue with the mega menu component.
How can i fire the dropdown on mouse hover. Also i want to have the current dropdown parent (in the main navbar) underlined.

Is there any option that can solve this problem?

Thanks.

**Comment by markchen1024** [comment]
Hi @BDZK , I have the same problem, ultimately I use `group` and `group-hover` instead.
https://dev.to/aasthapandey/group-hover-using-tailwind-css-4a2l

**Comment by Trochonovitz** [comment]
Hi, recently we dropped a new version of Tailwind Elements (actually beta but there were major changes). As @BubbleKID said, `group` and `group-hover` work for me.
