### ISSUE TITLE
NextJS installation procedure

### ISSUE THREAD

**Issue by ronlobo01** [mdbootstrap/TW-Elements#1075]
Need help with installing this in NextJS.

**Comment by Trochonovitz** [comment]
Hi, we just have launched bunch of integration tutorials - both with CSR and SSR frameworks. If you have more questions about integration or you still got some problems with particular components, let us know by adding [new issue](https://github.com/mdbootstrap/Tailwind-Elements/issues) / topic in [discussions section](https://github.com/mdbootstrap/Tailwind-Elements/discussions) (if there are some unclrear informations or just want let us know about something).

[Next.js integration tutorial](https://tailwind-elements.com/docs/standard/integrations/next-integration/).
