### ISSUE TITLE
Example code for Datepicker is wrong

### ISSUE THREAD

**Issue by sageworksstudio** [mdbootstrap/TW-Elements#1077]
[https://tailwind-elements.com/docs/standard/forms/datepicker/](https://tailwind-elements.com/docs/standard/forms/datepicker/)

The example text is wrong. `<input type="text"` should be `<input type="date"`

_Originally posted by @sageworksstudio in https://github.com/mdbootstrap/Tailwind-Elements/issues/1048#issuecomment-1279313468_

**Comment by smolenski-mikolaj** [comment]
Actually it's not the native date type element, but custom one.
