### ISSUE TITLE
Ripple does not work on Firefox 105

### ISSUE THREAD

**Issue by tvld** [mdbootstrap/TW-Elements#1078]
None of the ripple-effects on TE  [ripple doc page](https://tailwind-elements.com/docs/standard/methods/ripple/?#!) seem to work in Firefox. No color and no drop effect. All works however on the [Bootstrap page ](https://mdbootstrap.com/docs/standard/methods/ripple/)

Using FF v105 on Ubuntu 20.04 LTS

**Comment by smolenski-mikolaj** [comment]
Tested with the FF v107. Can you confirm the issue still exists?

**Comment by tvld** [comment]
Now it seems to work ))  
Closing...
