### ISSUE TITLE
React Carousel doesn't start INTERVAL always FALSE, wrong configuration

### ISSUE THREAD

**Issue by teshtek** [mdbootstrap/TW-Elements#1080]
Hi, there is a problem with configuration that receive tw-elements.

Here the import:
import 'tw-elements';

Usage:

`....<div data-bs-ride='carousel' data-bs-interval='1000' id='carousel' className='carousel slide carousel-fade relative'>....`

The slide is showing and also the indicators, on click it works, but it doesn't starts AUTOMATICALLY. 

<img width="416" alt="Schermata 2022-10-23 alle 11 02 33" src="https://user-images.githubusercontent.com/26298449/197383691-2fcd3848-524b-4b4f-86c8-e663b18f310e.png">

In debugging mode if we look inside config, there is an error:

<img width="290" alt="Schermata 2022-10-23 alle 11 03 39" src="https://user-images.githubusercontent.com/26298449/197383718-41e2ce3e-3397-4534-b7e0-644cb2e26b64.png">

The config is 👍 
```
{
    "ride": "carousel",
    "interval": false,
    "target": "#carousel",
    "slideTo": 1
}
```

so why interval is set to false?

<img width="346" alt="Schermata 2022-10-23 alle 11 06 51" src="https://user-images.githubusercontent.com/26298449/197383835-7d8d00c4-0b41-48b0-9979-8bb7a73955c5.png">

If I set new config it seems it takes them

`      <div data-bs-ride='carousel' data-bs-interval='1000' data-bs-touch='true' data-bs-pause='hover' data-bs-wrap='true' id='carousel' className='carousel slide carousel-fade relative'>
`
on the class carousel:

```
{
    "ride": "carousel",
    "interval": false,
    "touch": true,
    "pause": "hover",
    "wrap": true,
    "target": "#carousel",
    "slideTo": 1
}
```

Any idea?

**Comment by r-jacko** [comment]
I tried to recreate a problem but couldn't achieve this, please confirm if the problem still exists

**Comment by allan-navarro** [comment]
Hi, I'm seeing this behavior, the carousel wont start automatically
