### ISSUE TITLE
Site + All component bug ( automaticly hide ).

### ISSUE THREAD

**Issue by codecapsules** [mdbootstrap/TW-Elements#1081]
Hello i want to install your library but in your website i can't copy nothing.
All button 'show code' automaticly hide when we click it.
when i install the library all component with dynamic status automaticly hide when i click.
I test in my computer and in my mobile : same problem.
Can you see whats going on ? thanks you.

**Comment by smolenski-mikolaj** [comment]
The problem should be fixed with the latest release.

**Comment by DavithkbY** [comment]
> The problem should be fixed with the latest release.

I have a dropdown in my footer. On the first page it works fine but when I switch to a different page, when clicking it it opens very fast and then closes fast again. It's doesn't stay opened.
