### ISSUE TITLE
No component code is being copied 

### ISSUE THREAD

**Issue by prankurpandeyy** [mdbootstrap/TW-Elements#1084]
Impact : 
Whole website.
How to replicate : 
Go to any of the component and click on copy code button 
Expected Outcome : 
Should be able to copy the code on clipboard.
Real Outcome : 
Not able to copy the code as code snippet is hiding withing on second.

Workaroud : 
Tested on Mozzila /Chrome/Edge - Ubuntu /Windows

**Comment by prankurpandeyy** [comment]
I want to fix this issue , I have copied the code and installed the librs using npm install if anyone can help me to run it properly I believe that I would be able to fix it.

**Comment by smolenski-mikolaj** [comment]
The problem should be fixed with the latest release.
