### ISSUE TITLE
No  Component Code is visible after clicking show Code

### ISSUE THREAD

**Issue by kartikpavan** [mdbootstrap/TW-Elements#1086]

**Comment by sergiooak** [comment]
Same to Me.

During transition it is visible...
![image](https://user-images.githubusercontent.com/46563926/198315363-071d4437-3343-455e-b09e-c64e7a960909.png)

But when the transition finishes it disappears, 
![image](https://user-images.githubusercontent.com/46563926/198315511-c5ceb258-7e45-46fc-ad5c-31990b9eebdc.png)

I guess it is a CSS error

**Comment by sergiooak** [comment]
Found the cause, the propriety `visibility: colapse` on class `.collpase` is not working properly on Accordion Component
![image](https://user-images.githubusercontent.com/46563926/198317491-f00949d9-bc26-4493-acba-47420d47b7e8.png)

When I disability it, everything works just fine
![image](https://user-images.githubusercontent.com/46563926/198317050-cb462f31-0371-4583-9c87-492c648b81d8.png)
![image](https://user-images.githubusercontent.com/46563926/198317927-4773d786-5a0c-4953-857e-140f436dbd31.png)

**Comment by mario27** [comment]
Same problem.

**Comment by NotASKamDev** [comment]
Same issue

**Comment by myregistration** [comment]
Same.  And I was able to view per removing visibility: collapse style as well

**Comment by jdnichollsc** [comment]
Any help is really appreciated!

**Comment by tomokove** [comment]
because of this
https://github.com/tailwindlabs/tailwindcss/blob/master/CHANGELOG.md#320---2022-10-19
https://github.com/tailwindlabs/tailwindcss/pull/9181

**Comment by NicBeltramelli** [comment]
Same issue

**Comment by codecapsules** [comment]
Same issus.
Can you update the library more than one week we can't use your website or your library !!!
Thanks you.

**Comment by NotASKamDev** [comment]
Please fix site. I'm a noobie, and I can't learning anything from code I can't see.

**Comment by renatodex** [comment]
Oh, I was just going to open an Issue!
Thank you for reporting @kartikpavan !

**Comment by raihan71** [comment]
yeah same here @renatodex

**Comment by parko65** [comment]
Same here, can't copy sample code as it disappears

**Comment by Bastienbretenet** [comment]
Temporary solution while this library is updated  : revert to an earlier version of tailwindcss

`npm install -D tailwindcss@3.1.8`

**Comment by codecapsules** [comment]
> Temporary solution while this library is updated : revert to an earlier version of tailwindcss
> 
> `npm install -D tailwindcss@3.1.8`

Best solution for moment.

**Comment by smolenski-mikolaj** [comment]
The problem should be fixed with the latest release.
