### ISSUE TITLE
Tailwind-elements are not CSP complient

### ISSUE THREAD

**Issue by MichalKrakow** [mdbootstrap/TW-Elements#1088]
https://github.com/mdbootstrap/Tailwind-Elements/blob/master/src/scss/bs/_variables.scss#L916

Embedding encoded svg and other resources renders tw-elements unusable on sites with reasonable content security policies enabled.
There should be an option to use those, or just leave it to the end developer's bundler to decide if embedding is somenthing his project will benefit from.

**Comment by smolenski-mikolaj** [comment]
@MichalKrakow we're currently refactoring the code and going to remove all the bootstrap code from tailwind elements soon.
