### ISSUE TITLE
Problem with collapse class in navbar component

### ISSUE THREAD

**Issue by supersonicBlonde** [mdbootstrap/TW-Elements#1089]
With fresh install of tailwindcsss & tailwind element, with navbar component, **collapse class** is set on **_visibility: collapse_** on large viewport.

**Comment by makkinga** [comment]
Broke [here](https://github.com/tailwindlabs/tailwindcss/commit/cc1be47a4fa2de74bc63b0b123f335271ec1bc68) with Tailwind 3.2.0

**Comment by makkinga** [comment]
The suggested [solution](https://github.com/mdbootstrap/Tailwind-Elements/issues/1085#issuecomment-1294264945) in #1085 works well for now

**Comment by smolenski-mikolaj** [comment]
Hello, it was already fixed in the latest release.
