### ISSUE TITLE
info Tabs

### ISSUE THREAD

**Issue by zfranco55** [mdbootstrap/TW-Elements#1133]
premise: I am at the beginning (self-taught) of both front-end and back-end web programming.
I found your libraries very interesting and complete, because as a project to learn web programming I would like to use sveltekit, prism postrgeql with nodejs.
The code I need (to understand) how it all works I am looking for it on the internet, and more or less I am finding it,
Regarding Your library I would like to use, is that I have not found how to decrease the height of the Label tabs and how I can place them vertically on the right side.
Waiting in advance for a kind reply.
Sauti
Franco.
N.B. it's been a long time since I've seen any updates, I would not want the project to be dead, which I would be very sorry

**Comment by zfranco55** [comment]
Resolved.
All you had to do was read the manual of "flex-box" and Tailwindcss more thoroughly.
Anyway, I am curious if the project continues or is dead.

**Comment by zfranco55** [comment]
Anyway, I am curious if the project continues or is dead.

**Comment by smolenski-mikolaj** [comment]
The project continues. Here you can follow the status: https://github.com/orgs/mdbootstrap/projects/1/views/1
