### ISSUE TITLE
Uncaught SyntaxError: Invalid or unexpected token - all ui that need js like carousel, nav menu nav-pills, not working

### ISSUE THREAD

**Issue by bhojkamal** [mdbootstrap/TW-Elements#1167]
Hello, 
My junior developer is using tailwind css with tw-elements in my website on live. Flowbite is also added but tw-elements is used all or most. I think I should not use in my live website. I build and upload on live, It works for couple days and after couple days, It says ```Uncaught SyntaxError: Invalid or unexpected token``` on console. You can see the website too this [https://lotussoft.com.np/](https://lotussoft.com.np/)
My none component that need js is not working, even nav menu on mobile, carousel slider, accordion, nav nav-pills. 

Advice me for the solutions, otherwise, I need to remove tw-elements and use flowbite for  bootstrap. 

Thanks.

**Comment by smolenski-mikolaj** [comment]
Can't recreate the issue but with the lastest v1.0.0-beta1 version it should be fixed.
