### ISSUE TITLE
Input field default focus outline

### ISSUE THREAD

**Issue by MD-Mehedi-Hasan18111** [mdbootstrap/TW-Elements#1221]
When I'm install the tailwind elements library that time every input field getting default outline of library, I can't remove this default outline of input field. Please give me solution of this?

![image](https://user-images.githubusercontent.com/86622586/211214595-41424660-9af8-4043-813b-0d8d08ead074.png)

Thanks!

**Comment by smolenski-mikolaj** [comment]
We've just released the new v1.0.0-beta1 version and after update you will be able to change the color of the border in two ways:
- Customizing `primary` color
- Customizing classes from [this page](https://tailwind-elements.com/docs/standard/forms/inputs/#docsTabsAPI) that contains `primary` color to any other.
