### ISSUE TITLE
with nextjs not working

### ISSUE THREAD

**Issue by JavaidAhmadKhan** [mdbootstrap/TW-Elements#1238]
I tried Tawilwind elements with my couple of nextjs projects, but the functionality of opening modal, and accordions are not working however with create react app it is working it doesn't make any sense.

**Comment by cwikio** [comment]
Hi buddy, had same problem and also checked accordeon. and this sorted it out. https://stackoverflow.com/questions/71875270/how-to-install-the-tailwind-elements-in-nextjs 
have you seen it?

**Comment by JavaidAhmadKhan** [comment]
Yes, it works thanks a lot for your help buddy.
