### ISSUE TITLE
Please add React JSX under "Show Code"

### ISSUE THREAD

**Issue by cwikio** [mdbootstrap/TW-Elements#1243]
Hi there,
if it is not too much to ask, would it be possible to add JSX code alongside the HTML codes you already provide on your website? Just add another tab with React/JSX extension. I noticed if I copy/past the code the traditional comments syntax like   blows up React. Its easy, just need to delete it and it works like charm, but it would be so awesome if you could just add a tab, where these types of comments are deleted. Example [Login Form](https://tailwind-elements.com/docs/standard/components/login-form/)
Alternatively, delete all these types of comments.
Many thanks again for amazing work!

**Comment by Trochonovitz** [comment]
Hi, in nearest future we are going to start preparing standalone version of Tailwind Elements working with React so this problem will be resolved at this time.
