### ISSUE TITLE
Timepicker css can't be generate by Tailwind

### ISSUE THREAD

**Issue by vincentinttsh** [mdbootstrap/TW-Elements#1260]
I found that Tailwind will not generate the css Timepicker need.
This result is due to related css name of Timepicker is not code completely, but use concat.
EX: 
```
var m = "timepicker"
, iu = "".concat(m, "-time-tips-hours")
```

**Comment by smolenski-mikolaj** [comment]
We've just release the new v1.0.0-beta1 version synced with Tailwind 3.2.4 so after update the issue should be fixed.
