### ISSUE TITLE
Timepicker ignores data-mdb-timepicker-format24="true"

### ISSUE THREAD

**Issue by dieg092** [mdbootstrap/TW-Elements#1261]
Hello im trying to configure timepicker with 24 hours format. Attribute data-mdb-timepicker-format24="true" is ignored. Always show 12 hours format.

Code:
`<div class="timepicker " data-mdb-with-icon="false" data-mdb-timepicker-format24="true" id="data-mdb-timepicker-format24">
                                        <input type="text" 
                                        class="data-mdb-timepicker-format24 form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
                                        placeholder="Selecciona una hora" data-mdb-toggle="input-toggle-timepicker" />
                                    </div>`

Header:
` <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tw-elements/dist/css/index.min.css" />
    <script src="https://cdn.jsdelivr.net/npm/tw-elements/dist/js/index.min.js"></script>`

thanks!

**Comment by smolenski-mikolaj** [comment]
We've just release the new v1.0.0-beta1 version synced with Tailwind 3.2.4 so after update the issue should be fixed.
Keep in mind our data attributes change to `data-te-` syntax.
