### ISSUE TITLE
Default checked radio - not checked

### ISSUE THREAD

**Issue by flowoow** [mdbootstrap/TW-Elements#1270]
I'm trying to use the Radio input and have a default selection to one of the radio. However, the radio input is not checked.

From the documentation: https://tailwind-elements.com/docs/standard/forms/radio/
The Basic example has the same issue.

Default checked radio is not checked

**Comment by vinaysanga** [comment]
Fixed this issue in my pull request #1276

**Comment by smolenski-mikolaj** [comment]
We've just release the new v1.0.0-beta1 version so after update the issue should be fixed.
