### ISSUE TITLE
Migration from Webpack to Vite

### ISSUE THREAD

**Issue by smolenski-mikolaj** [mdbootstrap/TW-Elements#1279]

**Comment by juujisai** [comment]
1. Migration to Vite and removing Webpack related dependencies
2. Start demo app on Vite and test documentation if everything is working fine
3. Compare Webpack and Vite builds file weight
4. Vite integration instruction - new documentation page and sidenav section
5. Add new commands (init and start)
6. Add a license disclaimer to compiled files
