### ISSUE TITLE
nuxt3 

### ISSUE THREAD

**Issue by Ischafak** [mdbootstrap/TW-Elements#1282]
Hi, i am working on nuxt3 (version 3.1.0)

i am trying to import twelements like this 

import * as twelements from 'tw-elements/dist/js/index.min.js';

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(twelements);
});

and i am getting this error 
Uncaught SyntaxError: The requested module '/_nuxt/node_modules/.vite/deps/tw-elements_dist_js_index__min__js.js?v=8f06cfac' does not provide an export named 'default' (at twelements.client.js:1:1)

can you please help me?

**Comment by w3bdesign** [comment]
Try:

`import {Element} from "tw-elements"`

**Comment by Ischafak** [comment]
@w3bdesign first of all thank you for your answer

i tried this after your suggestion but sadly not working

```
import {Element} from "tw-elements"
export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(Element);
});
```

this is the error code same i think
Uncaught SyntaxError: The requested module '/_nuxt/node_modules/.vite/deps/tw-elements.js?v=771b4213' does not provide an export named 'default' (at twelements.client.js:1:1)

**Comment by Ischafak** [comment]
import * as twelements from 'tw-elements/dist/js/index.min.js';

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(twelements);
});

i dont know will this help you but this code were working on previous 3.0.0-rc.11 nuxt version and 1.0.0-alpha12 twelements version but now nuxt3 has a stable version(3.1.0) and i cant import twelements

**Comment by w3bdesign** [comment]
@Ischafak 

Element was just an example

Try importing the component you are trying to use inside the code

**Comment by Ischafak** [comment]
Ok thanks i will try

Can i just import all components something like this
import * as twelements from "tw-elements"

**Comment by Ischafak** [comment]
sadly it is not working

**Comment by w3bdesign** [comment]
@Ischafak 

Can you either provide a link to the repo or a minimally reproducible sandbox?

**Comment by Ischafak** [comment]
I created this 
https://codesandbox.io/s/clever-williams-qbdwc9?file=/sandbox.config.json

when you open your browsers console (not console tab on the website) you will see the error i am facing with. about the other errors i am not seeing them in my own project its not about that i think

and same code is working on "nuxt version 3.0.0-rc.11"

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/13226879/217192906-bc726324-bff8-4bc3-a2f8-a39dc858b3ce.png">



<img width="1440" alt="image" src="https://user-images.githubusercontent.com/13226879/217191656-3333a383-e4a6-4264-a920-7bae97ac465f.png">

**Comment by faustino21** [comment]
for the meantime you can use the script on cdn link and use it on nuxt.config.ts 
`
export default defineNuxtConfig({
    modules: ['@nuxtjs/tailwindcss'],
    app: {
        head:{
            script : [
                {src : "https://cdn.jsdelivr.net/npm/tw-elements/dist/js/index.min.js"}
            ]
        }
    },
    postcss: {
        plugins: {
          tailwindcss: {},
          autoprefixer: {},
        },
    },
})

`

this is work for me.

**Comment by faustino21** [comment]
For the meantime you can use the link on cdn script tag and use it on nuxt.config.ts

```
export default defineNuxtConfig({
    modules: ['@nuxtjs/tailwindcss'],
    app: {
        head:{
            script : [
                {src : "https://cdn.jsdelivr.net/npm/tw-elements/dist/js/index.min.js"}
            ]
        }
    },
    postcss: {
        plugins: {
          tailwindcss: {},
          autoprefixer: {},
        },
    },
})
```

this is work for me.

**Comment by Trochonovitz** [comment]
Hi, we just have launched bunch of integration tutorials - both with CSR and SSR frameworks. If you have more questions about integration or you still got some problems with particular components, let us know by adding [new issue](https://github.com/mdbootstrap/Tailwind-Elements/issues) / topic in [discussions section](https://github.com/mdbootstrap/Tailwind-Elements/discussions) (if there are some unclear informations or just want let us know about something).

[Nuxt integration tutorial](https://tailwind-elements.com/docs/standard/integrations/nuxt-integration/).

**Comment by Ischafak** [comment]
Sorry for reopenin. I have checked ssr documentation but it is a bit old i guess. Still i cant find anyway to fix this problem.

**Comment by Trochonovitz** [comment]
@Ischafak first of all - if you are working in Codesandbox, you got to update library. Second: this way of importing Tailwind Elements (from original post) does not work anymore. If you are still have problems with implementation TE, try also import CSS file in `app.vue`.

`import "tw-elements/dist/css/tw-elements.min.css";`

**Comment by Ischafak** [comment]
@Trochonovitz sorry for your time i am not very good at these kind of things.
i tried something like this
https://codesandbox.io/p/sandbox/funny-grass-busss4?file=%2Fpages%2Findex.vue&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A63%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A63%7D%5D
and there is still an error. if possible can you tell me what am i doing wrong?

for now i want to add all components globally

**Comment by Mayanktaker** [comment]
I can confirm none of these is working and not even the official installation guide. Tried with cdn version also. Not working with Nuxt 3.5.2. 
` "tw-elements": "^1.0.0-beta2"`

**Comment by Ischafak** [comment]
Still i cant find and answer please someone help me

**Comment by Ischafak** [comment]
i tried to update both nuxt and twelements now i am using 
"tw-elements": "1.0.0-beta3",
"nuxt": "3.6.5",

i tried multiple things none of these worked

it says ReferenceError: document is not defined

**Comment by Ischafak** [comment]
<script setup>
    onMounted(async () => {
    const { Datepicker, Input, initTE } = await import("tw-elements");
    initTE({ Datepicker, Input });
  });
</script> 
if i add something like this it works

but i dont want to add all pages again and again is it possible for me to add all components once
@Trochonovitz
