### ISSUE TITLE
The document is unreadable.

### ISSUE THREAD

**Issue by otowa552** [mdbootstrap/TW-Elements#1387]
JavaScript on the site is not working.
Can go to each component page from the search, but cannot open the sample code.

**Comment by 0xearl** [comment]
is it the same as mine? #1389

**Comment by smolenski-mikolaj** [comment]
Please make full refresh with `ctrl + shift + r`.

**Comment by smolenski-mikolaj** [comment]
The fix to force reloading JS file has just been deployed.
