### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'hasAttribute')

### ISSUE THREAD

**Issue by 0xearl** [mdbootstrap/TW-Elements#1389]
It seems that https://cdn.jsdelivr.net/npm/tw-elements/dist/js/index.min.js is having an error when initializing 
![image](https://user-images.githubusercontent.com/58910880/220280910-0373cc20-8acf-4590-a00e-721be1b0f869.png)
it errors on this part 
![image](https://user-images.githubusercontent.com/58910880/220280992-400be75a-b3f6-4a43-a2f5-e8df1def0bc9.png)
where it checks whether the website has jQuery and It the body doesn't have an attribute of "data-te-no-jquery".
but when I tried checking it on my console. It returns perfectly fine
![image](https://user-images.githubusercontent.com/58910880/220281293-ecdbd90f-7c64-4d39-9c3c-6d8a8e78b6f3.png)

**Comment by smolenski-mikolaj** [comment]
How can I recreate the issue? I can't see this error in the console when initializing.

**Comment by 0xearl** [comment]
@smolenski-mikolaj i'm not sure as well, but on my local machine everything looks fine. 
there's just this error here but every tailwind-elements component are still working fine.
![image](https://user-images.githubusercontent.com/58910880/220285048-9e5dc345-5205-45b9-bfa0-a1e89ef2c360.png)

it's just that the same code works on my local but when i pushed it to dev it errors out

**Comment by smolenski-mikolaj** [comment]
It weird because the document.body can't be null. Maybe you should move the script to the end part of the file, just before the body closing tag?

**Comment by 0xearl** [comment]
the script is on the footer.

**Comment by smolenski-mikolaj** [comment]
It's definitely something wrong with the project's architecture. There is no way document.body is null in typical application.

**Comment by 0xearl** [comment]
@smolenski-mikolaj, the issue is this actually. and not the body being null (that's my local machine and the elements still works)
![image](https://user-images.githubusercontent.com/58910880/220306742-5f03e9fa-9fdb-4f11-a599-fd9c18ba9b51.png)
this on the other hand makes the tw-elements not work.

**Comment by 0xearl** [comment]
![image](https://user-images.githubusercontent.com/58910880/220308848-978b9dde-0d0a-40bc-bd6c-6839c0ff7391.png)
more context on this error
the images you're seeing is a https://tailwind-elements.com/docs/standard/components/carousel/. and since the index.js has error it doesn't look right.

**Comment by 0xearl** [comment]
![image](https://user-images.githubusercontent.com/58910880/220311434-ca94ee59-8c7a-4f51-b9d3-978b93bfe4a2.png)
same code, but it works correctly

**Comment by 0xearl** [comment]
upon digging deeper into this, I found out that to replicate this, on my local machine I have to comment out the CSS.
![image](https://user-images.githubusercontent.com/58910880/220510990-71262d30-c88b-4a1c-bdfc-3892958b50cc.png)

but on my dev server the CSS loads fine.

**Comment by 0xearl** [comment]
i'll close this, as this was because of the tw-elements/index.min.css version changes.
