### ISSUE TITLE
Multiselect doesn't work

### ISSUE THREAD

**Issue by MarianaThainara** [mdbootstrap/TW-Elements#1410]
Hi,
The new multiselect is not working as expected 😥. When I copy the basic example from the documentation and test it in my project, the field doesn't appear styled, just the default html. How can I fix it?

**Comment by smolenski-mikolaj** [comment]
@MarianaThainara what is your environment? Does any other advanced component work in your app? Did you add JS file to your project?

**Comment by smolenski-mikolaj** [comment]
Closing due to lack of response.
