### ISSUE TITLE
Is tailwind elements support to use with react?

### ISSUE THREAD

**Issue by siamahnaf** [mdbootstrap/TW-Elements#1422]
Hello, I am not finding any documentation for using with react. Can anyone give me to use react.

I have a features request-

Can we get a react version of tailwind elements. Then please add support like-

```
import {Input} from "tw-elements"

const Home =()=> {
   return (
     <Input label="Phone Number" />
  )
}
```

**Comment by Trochonovitz** [comment]
Hi, there is no additional version of Tailwind Elements supporting React but we are plannig to create it. For now you can add useEffect hook in App.jsx file for dynamic import of library. Also we are going to create dedicated page for integration TE with most popular CSR and SSR frameworks but I cannot say ETA on this yet.

```
  useEffect(() => {
    const use = async () => {
      await import("tw-elements");
    };
    use();
  }, []);
```

**Comment by siamahnaf** [comment]
Okay, we are waiting. React version of tailwind elements.

If I want to contribute, then how can I do that?

**Comment by Trochonovitz** [comment]
Thanks for commitment! I believe we are going to release a stable beta in a nearly future and then allow users to contribute. But this is not written in stone so things could change.
