### ISSUE TITLE
Datepicker - Clear should set active date to null

### ISSUE THREAD

**Issue by jdnichollsc** [mdbootstrap/TW-Elements#1429]
**Describe the bug**
Clear button from **Datepicker** is not notifying the selected date when user confirm it's **null**.

**Expected behavior**
Clear the date when the **Clear** button is pressed and user confirm.

**Actual behavior**
We can't clear the date and confirm that null selection

**Comment by jdnichollsc** [comment]
Ok, I was testing and the problem is that we don't allow to clear the date, that's important to be able to notify that confirmation

**Comment by jdnichollsc** [comment]
I'm wondering if we can revert the date selection if the cancel button is pressed after the clear button, what do you think folks? <3

**Comment by smolenski-mikolaj** [comment]
Actually we define the Datepicker dialog as sort of a "step by step date creator". When you choose a date by picking a day it's just a first step. Then you can still choose cancel to prevent date change in input, or choose OK to submit picked date. Also, you can still set clear to cancel the selection (which is not same as cancelling the date change state). At this moment, we don't want to make any changes to pickers as it's too soon after last release. But will be monitoring the situation and issues.
