### ISSUE TITLE
[select] [Placeholder is only shown when using multiple select]

### ISSUE THREAD

**Issue by rabol** [mdbootstrap/TW-Elements#1440]
**Describe the bug**
Placeholder is only shown wne one include the 'multiple'

**To Reproduce**

this does not have a placeholder
```
<select
    data-te-select-init
    data-te-select-placeholder="Select level"
    id="user_level"
    name="user_level">
        <option value="10">Standard</option>
        <option value="20">Plus</option>
        <option value="30">Pro</option>
</select>
```

this have a place holder
```
<select
    data-te-select-init
    data-te-select-placeholder="Select level"
    multiple
    id="user_level"
    name="user_level">
        <option value="10">Standard</option>
        <option value="20">Plus</option>
        <option value="30">Pro</option>
</select>
```

**Expected behavior**
Expected tha the select will have a placeholder.

**Actual behavior**
The select does not have the placeholder

**Show your code**
see above - cannot create snippet as my account needs to be 7 day old!
issue is also in the snippet on the playground

**Comment by Trochonovitz** [comment]
Hi, I believe you are talking about [Hidden selected option](https://tailwind-elements.com/docs/standard/forms/select/#hidden-selected-option) example.

**Comment by rabol** [comment]
I'm simply trying to have a placeholder in the select, and it only appears if I add 'multiple', but then the select becomes a multiple select, which I don't want

https://tailwind-elements.com/docs/standard/forms/select/#select-with-placeholder

**Comment by Trochonovitz** [comment]
This is on purpose - example linked above, Hidden selected option, has only one selected element + placeholder.

**Comment by rabol** [comment]
> Hi, I believe you are talking about [Hidden selected option](https://tailwind-elements.com/docs/standard/forms/select/#hidden-selected-option) example.

No I'm talking about: https://tailwind-elements.com/docs/standard/forms/select/#select-with-placeholder


so I cannot have a placeholder in a 'single' select ?
