### ISSUE TITLE
[Text Inputs] [borders not work]

### ISSUE THREAD

**Issue by seingod** [mdbootstrap/TW-Elements#1496]
hi 
i want use text element
i use vite vue js
and get this errors when click on the element
![image](https://user-images.githubusercontent.com/113516369/226147068-2248a9f9-35f1-4150-bfce-04079067ce9d.png)

**Comment by Odex64** [comment]
same here

**Comment by smolenski-mikolaj** [comment]
Please check the following solution:

```       
          import { onMounted } from "vue";

          onMounted(() => {
            const importTE = async () => {
              await import("tw-elements");
            };
            importTE();
          });
```

**Comment by deviantfero** [comment]
I'm trying to use inputs in a django project and getting this exact same error, how would I go around fixing it there? @smolenski-mikolaj 

I'm already importing the relevant javascript file as the documentation indicates.

**Comment by smolenski-mikolaj** [comment]
@deviantfero Did you follow our guide?
https://tailwind-elements.com/docs/standard/integrations/django-integration/
