### ISSUE TITLE
Unify Chips init

### ISSUE THREAD

**Issue by smolenski-mikolaj** [mdbootstrap/TW-Elements#1538]
https://github.com/mdbootstrap/Tailwind-Elements/blob/master/src/js/components/chips/index.js#L663
https://github.com/mdbootstrap/Tailwind-Elements/blob/master/src/js/components/chips/chip.js#L189

**Comment by juujisai** [comment]
https://github.com/mdbootstrap/Tailwind-Elements/pull/1769
