### ISSUE TITLE
Can't change the border color of the select element.

### ISSUE THREAD

**Issue by memiljamel** [mdbootstrap/TW-Elements#1543]
Hi, I'm trying to change the border color of a select element. i see in API section there is no **"classes"** to change border color. i know that border color can be changed on input element using **"data-te-class-notch-leading-normal/data-te-class-notch-middle-normaldata-te-class-notch-trailing-normal"** and it works. similar thing can also be applied to element datepicker or timepicker, but element select doesn't work. how can i overcome this?

![tempsnip](https://user-images.githubusercontent.com/45848997/229272282-fb897d9d-fdb6-4192-8387-e88fc267ffca.png)

![Capture](https://user-images.githubusercontent.com/45848997/229272361-36f54cb2-a42f-44ac-a52d-467454b47dc6.PNG)

**Comment by RenaldiPranata** [comment]
any update?

**Comment by juujisai** [comment]
@RenaldiPranata We are going to work on it soon and should be ready for the next release.
