### ISSUE TITLE
Clipboard

### ISSUE THREAD

**Issue by smolenski-mikolaj** [mdbootstrap/TW-Elements#1561]

**Comment by eioluseyi** [comment]
Hi @smolenski-mikolaj I would like to get on this.
I am asking, as the docs said to, before beginning

**Comment by juujisai** [comment]
Hi @eioluseyi thank you but I'll assign someone from our team since we already have created foundaments for those components. Best Regards!

**Comment by eioluseyi** [comment]
Alright @juujisai 
Thanks
