### ISSUE TITLE
CSS file not found

### ISSUE THREAD

**Issue by gunjankpsl** [mdbootstrap/TW-Elements#1584]
Url not working https://cdn.jsdelivr.net/npm/tw-elements/dist/css/index.min.css shows not found.

Is anything updated on your end??

**Comment by smolenski-mikolaj** [comment]
Please use the updated paths:
https://tailwind-elements.com/docs/standard/getting-started/quick-start/#cdn

https://cdn.jsdelivr.net/npm/tw-elements/dist/css/tw-elements.min.css
https://cdn.jsdelivr.net/npm/tw-elements/dist/js/tw-elements.umd.min.js
