### ISSUE TITLE
index.js is missing

### ISSUE THREAD

**Issue by makindajack** [mdbootstrap/TW-Elements#1585]
**The file is missing in the dist folder**
the documentation says,"<script src="../node_modules/tw-elements/dist/js/index.min.js"></script>" should be added, but its missing in node_modules folders

**Expected behavior**
Js function to work.

**Actual behavior**
The components look broken.

**Desktop**

- OS: [e.g. Mac OS, Windows]
- Browser [e.g. MS Edge, safari]

**Comment by smolenski-mikolaj** [comment]
@makindajack We added new file format, so JS and CSS files changed it's names. Please check the docs:
https://tailwind-elements.com/docs/standard/getting-started/quick-start/#formats

You can now use `dist/js/tw-elements.umd.min.js` or `dist/js/tw-elements.es.min.js` JS files.

**Comment by KrunalDatascience** [comment]
I am trying to use this module in Nuxt3. It is giving **ReferenceError: document is not defined** error. I also tried to solve it by importing the module in my component this way:

```
<script setup>
  import { onMounted } from 'vue'

  onMounted(() => {
    if (process.client) {
      import('tw-elements')
    }
  })
</script>
```

still it fails to work.

**Comment by smolenski-mikolaj** [comment]
@KrunalDatascience did you follow our Nuxt integration guide?
https://tailwind-elements.com/docs/standard/integrations/nuxt-integration/

**Comment by KrunalDatascience** [comment]
> @KrunalDatascience did you follow our Nuxt integration guide? https://tailwind-elements.com/docs/standard/integrations/nuxt-integration/

@smolenski-mikolaj : It is working fine after i followed the guide. I was trying to import the plugin within /plugins/twelements.client.js to set the default behavior of initializing components at client side and avoid writing \<ClientOnly> (like it is suggested in the guide.)

Anyway i am an absolute beginner to vue/nuxt and may not know what am i saying.!
