### ISSUE TITLE
cannot found directory "plugin" in root folder of package

### ISSUE THREAD

**Issue by manhcuong130295** [mdbootstrap/TW-Elements#1589]
cannot found directory "plugin" in root folder of package
It only file plugin.cjs
config in file taiwind.config.js is error when run yarn prod/yarn watch

**Comment by smolenski-mikolaj** [comment]
After the last release it should be plugin.cjs instead plugin.js. Please check the docs:
https://tailwind-elements.com/docs/standard/getting-started/quick-start/
