### ISSUE TITLE
Accessing the current state of the component - closing Mega Menu @mouseleave

### ISSUE THREAD

**Issue by KrunalDatascience** [mdbootstrap/TW-Elements#1592]
I am working with Mega Menu, and I want to set the behavior of closing it \@mouseleave. Does it expose the current state of the component through v-slot like it does in another ui package: [HeadlessUI](https://headlessui.com/vue/popover#using-slots) . Or is there any other way to close the mega menu when i am moving out of its pannel?

**Comment by juujisai** [comment]
You can close the mega menu by listening for `mouseleave` event and then calling the `hide` method provided by `Dropdown`.  

If you were to use the basic example of mega menu ( https://tailwind-elements.com/docs/standard/navigation/mega-menu/#basic ) and add `megamenu-dropdown` id to the element that have the `data-te-dropdown-menu-ref` data attribute (so our mega menu), you can make it work by adding the code below to your javascript file (after `initTE` if you are using `ES` format)

```
const dropdownElement = document.querySelector("#dropdownMenuButtonX");
const myDropdown = Dropdown.getOrCreateInstance(dropdownElement);

document
  .querySelector("#megamenu-dropdown")
  .addEventListener("mouseleave", () => {
    myDropdown.hide();
  });
```
  
As of the current state, the dropdown menu (`data-te-dropdown-menu-ref`, mega menu) will receive `data-te-dropdown-show` attribute if it is open and will lose it if it's closed.   
  
You can also listen to the events, to see what is happening with the component: 
https://tailwind-elements.com/docs/standard/components/dropdown/#api-section-events
