### ISSUE TITLE
Use in Astro possible?

### ISSUE THREAD

**Issue by silveltman** [mdbootstrap/TW-Elements#1639]
I don't see anything on this in the docs. I don't totally get how the library works, are the components initialised with JavaScript?

Is it possible to import these components into Astro? Or maybe into sveltekit > make that a component library > import that in Astro?

Thanks!

**Comment by smolenski-mikolaj** [comment]
For this moment we don't provide support for Astro. According Svelte we recommend our [tutorial](https://tailwind-elements.com/docs/standard/integrations/svelte-integration/).
