### ISSUE TITLE
Datepicker - Inline datepicker throws error when using a custom container

### ISSUE THREAD

**Issue by micbenner** [mdbootstrap/TW-Elements#1667]
When using the datepicker, if you use the `inline` picker with a customer `container` option, you will receive the following error:

`Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

Inside the `_closeDropdown()` method, the code is attempting `document.body.removeChild(datepicker)` on the `body` element. Since the `container` option has changed the parent element (the parent is no longer `body`) this method throws an error.

https://github.com/mdbootstrap/Tailwind-Elements/blob/dafbb6906a2829a32a9267df082fabb94baca992/src/js/forms/datepicker/index.js#L1114-L1135

**To Reproduce**
1. Create a new Datepicker
2. Set the `container` option to something other than the body
3. Set `inline: true`

**Comment by juujisai** [comment]
Hi! Thanks for letting us know! I have added this issue to our project list so we can fix it. Best Regards!
