### ISSUE TITLE
[Form] [labels doesn't work]

### ISSUE THREAD

**Issue by carolinamorah** [mdbootstrap/TW-Elements#1682]
I'm using the form component for the login on my website, but sometimes the blue border of the input stops working, and the label overlaps the input and covers the content. How do I solve this issue? How can I make the label animation and the blue border when focusing on the input continue to work? Sometimes, when I reload the page, it stops working.

**Comment by juujisai** [comment]
Hi, could you give us more info like:

- When does this happen,
- What kind of stack you work on,
- Is there some specific window or input width where you are experiencing this issue or is it everytime,
- What kind of device and browser are you using? Are you using the newest `tw-elements` package?
- Maybe you could show us some code, or create a snippet? https://tailwind-elements.com/snippets/

Best Regards!

**Comment by pkvov** [comment]
I finally figured out that all input forms should be initialized using initTE

```
Required ES init:
Input
*
* UMD autoinits are enabled by default. This means that you don't need to initialize the component manually. However if you are using Tailwind Elements ES format then you should pass the required components to the initTE method.
```
