### ISSUE TITLE
Select component duplication 

### ISSUE THREAD

**Issue by kingdomac** [mdbootstrap/TW-Elements#1696]
The same Select component appears 2 times while is imported only once.

I am working with nuxt 3 js, i realised that when using the Tab component with the Select component the second one is initalized more then one time, which will reproduce repetition for the Select component.

**Comment by juujisai** [comment]
Hi, could you maybe show us some code or maybe give more clues on how to recreate this? I've tried to put the select component outside the tab component and inside one of its tabs and didn't see the issue. I may have missed something here.  

Or maybe you mean the element with `data-te-select-wrapper-ref` attribute next to the native `select` element? This one is ok, since we want to keep the native select in case of disposing the Tailwind Elements Select.

Best Regards!

**Comment by kgallarin** [comment]
Hello first of all thanks for the awesome plugin! I also experience this issue when changing page when returned to the page where the `select component` resides, it seems being re-rendered again. I also try doing it multiple times but it duplicates once (until 2 elements). I only have these simple component for trying it out, thanks a lot in advance!


```js
<select
        data-te-select-init
        data-te-class-select-input="rounded-md text-base py-[10px] w-full px-[11px] border border-[#dcdcdc] focus:outline-none leading-[1.4em]"
        data-te-class-form-outline="relative bg-[transparent] border-none focus:outline-none"
        data-te-class-options-list="font-normal"
        data-te-class-select-arrow="absolute right-3 top-[15px] text-[0.8rem] cursor-pointer text-[#dcdcdc] w-5 h-4"
        data-testid="select1" 
        name="select1" 
                        >
          <option value="1">Option 1</option>
          <option value="2">Option 2</option>
      </select>


<script setup>
    import { Select, initTE } from "tw-elements"
    import { onMounted } from 'vue'

    onMounted(() => {
        initTE({ Select })
    })
</script>
```

I'm using these versions:
  "tw-elements": "^1.0.0-beta2",
  "vite": "^4.0.0",
  "vite-plugin-s3": "^1.0.2",
  "vue": "^3.2.31",

![Screen Shot 2023-07-03 at 15 52 16](https://github.com/mdbootstrap/Tailwind-Elements/assets/1480731/3ffece9e-b8e0-482f-9636-af6f9d0c1c07)
![Screen Shot 2023-07-03 at 15 52 24](https://github.com/mdbootstrap/Tailwind-Elements/assets/1480731/d38bf201-4890-4d00-93cf-6e24836a27db)

**Comment by juujisai** [comment]
@kgallarin do you have anything else in a `template` where you put the select component? I tried to play a bit with routing and new vue app and when inside my `view` page I had only the select component it started to init everytime I changed the route. When i added even an empty `<span></span>` it stopped doing this. Maybe you could give it a try?

The other thing to try is to maybe check whether the initTE was already called inside the component:
```
const inited = ref(false);

onMounted(() => {
  !inited.value && initTE({ Select });
  inited.value = true;
});
```

... or maybe add a wrapper for select and check if inside the wrapper there is already an element with `data-te-select-wrapper-ref` attribute?

**Comment by kgallarin** [comment]
Thanks for your time and support @juujisai! Worked like a charm
