### ISSUE TITLE
[Doc] [typo in Ripple page]

### ISSUE THREAD

**Issue by tlagoda** [mdbootstrap/TW-Elements#1697]
**Describe the bug**
There is a typo in the ripple page. It's written `Wsing` instead of `Using`.

**To Reproduce**

1. Go to [Ripple page](https://tailwind-elements.com/docs/standard/methods/ripple/)
2. Scroll down to 'Image section'
3. See error

**Expected behavior**
`Using data-te-ripple-init attribute you can also easily add the ripple effect to images.`

**Actual behavior**
`Wsing data-te-ripple-init attribute you can also easily add the ripple effect to images.`

**It might be a good idea to mark this as a 'good first issue'.**

**Comment by juujisai** [comment]
Hi! Thank you, I fixed the typo. Best Regards!

**Comment by tlagoda** [comment]
Perfect!
