### ISSUE TITLE
Tooltip and Popover not working via data attributes and Angular (v16) and tw-elements beta2

### ISSUE THREAD

**Issue by osahner** [mdbootstrap/TW-Elements#1698]
> ng new app-test --style=scss --routing=true --skip-git --inline-style --standalone
> cd app-test
> yarn add --dev tailwindcss postcss autoprefixer
> npx tailwindcss init

edit  tailwind.config.js
add Tooltip / Popover as described in the documentation.
tried variations with: ```initTE({ Tooltip, Popover });``` with the same result.

```
  "dependencies": {
    ...
    "@angular/core": "^16.0.0",
    ...
    "tw-elements": "^1.0.0-beta2",
    ...
  },
```

However, the initialisation with JS works.

**Comment by juujisai** [comment]
Hi, Tooltips and Popover do not have autoinits added for now. I'll add this to our project list. Best Regards!
