### ISSUE TITLE
Scrollspy - The requested module [path-to-compiled-js] does not provide an export named 'Scrollspy' when using Vite

### ISSUE THREAD

**Issue by angelo-myhealthafrica** [mdbootstrap/TW-Elements#1717]
Using the example code in the [Scrollspy documentation](https://tailwind-elements.com/docs/standard/navigation/scrollspy/#basic) to import Scrollspy module, the following error is logged on the console: 
```
Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/tw-elements.js?v=e144d672' does not provide an export named 'Scrollspy' (at local-profile.js:1:10)
```
and the Scrollspy element is not initialized.

local-proile.js:
```
import { Scrollspy, initTE } from "tw-elements";

initTE({ Scrollspy });
```

my-page.blade.php:
```
...
`@vite('resources/js/local-profilelocal-profile..js')`
...
```

However, changing _local-profile.js_ to be:
```
import { ScrollSpy, initTE } from "tw-elements";

initTE({ ScrollSpy });
```
resolves the issue.

**Comment by juujisai** [comment]
Hi! Thank you for letting us know. I have updated our documentation. Best Regards!
