### ISSUE TITLE
In file index.html, line 37, the use of that style tag is useless

### ISSUE THREAD

**Issue by uniiquecornnx** [mdbootstrap/TW-Elements#1790]
**Describe the bug**
Not really a bug, but in line 37, the style tag is useless

**Expected behavior**

**Actual behavior**
A clear and concise description of what is happening instead.

**Show your code**
It will be easier for us to help you if you [create a snippet using TE playground](https://tailwind-elements.com/snippets/) and include a link to it in your issue.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Make sure it is indeed an issue/bug report**

- If it's a general support question (you just can't figure out how something works), but not an issue with the UI Kit or documentation itself it's better to ask here:
  https://github.com/mdbootstrap/Tailwind-Elements/discussions/categories/support-from-community
- If it's an idea for a new feature, but you cannot write the code for it yourself, it's better to ask here:
  https://github.com/mdbootstrap/Tailwind-Elements/discussions/categories/share-ideas-request-features
- If it's general feedback, it's better to post it here:
  https://github.com/mdbootstrap/Tailwind-Elements/discussions/categories/kind-words-general-feedback

**Comment by juujisai** [comment]
Hi, you mean this one? 
https://github.com/mdbootstrap/Tailwind-Elements/blob/master/index.html

This is just a demo page for our components. This file is not landing in the package.
