### ISSUE TITLE
[Solved] Offcanvas not defined, te not defined

### ISSUE THREAD

**Issue by christoferd** [mdbootstrap/TW-Elements#1839]
**Don't know if this is a bug:**
None of the code from Offcanvas API Javascript code works, however the default Offcanvas demo code works perfectly.
TALL stack
Any info on how I can troubleshoot this would be greatly appreciated.

![image](https://github.com/mdbootstrap/Tailwind-Elements/assets/1835883/9a823cc7-151b-487b-85ee-1f0b6eb2d11a)

Note: I also tried using a button with onclick and the code leading to the same error messages.

**To Reproduce**
Pull [repo with example code](https://github.com/christoferd/test-te-li-july-2023) to current empty folder
`composer install`
`npm install`
Run vite/npm asset builder: `npm run dev`
Run PHP server: `php artisan serve`
Test - it works: [http://127.0.0.1:8000/](http://127.0.0.1:8000/)
Click on the buttons that are marked as working
Open Dev Tools
Click on the button that is marked as _not_ working

**Expected behavior**
Expecting "Offcanvas" to be an object that is instantiable from JS
Or, "te" (UMD)

**Actual behavior**
Only see errors.

**Show your code**
app.js
```import './bootstrap';
import Alpine from 'alpinejs';
import focus from '@alpinejs/focus';
import { Offcanvas, initTE } from "tw-elements";
initTE({ Offcanvas });
window.Alpine = Alpine;
Alpine.plugin(focus);
Alpine.start();
```

**System:**
- OS: Windows 11
- Browser Latest Chrome/Brave
- nodejs v18.16.1

**Make sure it is indeed an issue/bug report**
I searched google for "tailwind elements offcanvas not defined", github discussions and github issues for "not defined"

**Comment by juujisai** [comment]
I'm not sure if that would help but I have few ideas:
- if your app is using UMD format. you can try importing the package like this: `import "tw-elements"` or `import * as te from "tw-elements`
- in some of JS frameworks, dynamic importing of the package helped. For example: `const { Offcanvas, initTE } = await import("tw-elements")`
- try importing the package when your code loads / mounts. Same as before, I do not have experience with TALL stack, but maybe there is something similar to `onMounted` from vue or `useEffect` from react


Does the error show for the `initTE` method aswell?

**Comment by christoferd** [comment]
@juujisai Thanks for the tips. None of that managed to work.

I have updated my demo repo to include 2 buttons now. ES / UMD for quicker testing.

Note also - for some reason the ES JS code is now the same as UMD code on [the Offcanvas API page](https://tailwind-elements.com/docs/standard/navigation/offcanvas/#docsTabsAPI) under Via JavaScript
Wondering now if someone is in the process of testing and fixing :-/

**Comment by juujisai** [comment]
The code under Via JavaScript is almost the same. The only difference is that in ES format you have to import the `Offcanvas` as shown in the `Import` section. In UMD format you don't import the Offcanvas, only the package as a whole. You have to access it from the `te` variable. 

I just downloaded the TE starter and for me everything is working properly (vanilla JS). 

We have bunch of integration tutorials on our docs page here: https://tailwind-elements.com/docs/standard/integrations/angular-integration/

Maybe there would be something that would help in your case?

BTW, did you check if console logging any of the `te` or `initTE` shows anything? You can even check if dynamic imports after some timeout show anything.

**Comment by christoferd** [comment]
**"BTW, did you check if console logging any of the te or initTE shows anything?"**

Interesting, in **app.js** the objects exist, but not accessible on the web page.

```
import './bootstrap';
const { Offcanvas, initTE } = await import("tw-elements");
initTE({ Offcanvas });
console.log('initTE', initTE);
console.log('Offcanvas', Offcanvas);
```

Showing that the console log in app.js works, but then trying to do the same directly in Dev Tools throws an error.
![image](https://github.com/mdbootstrap/Tailwind-Elements/assets/1835883/b7071a56-1ecd-4ceb-9336-50db9476832f)

All assets loading correctly
![image](https://github.com/mdbootstrap/Tailwind-Elements/assets/1835883/197ddb7a-1c4a-40bd-b29e-d5bddb273f25)

app.js from within Dev Tools
![image](https://github.com/mdbootstrap/Tailwind-Elements/assets/1835883/0350b256-c795-4754-9563-45830977b8e8)

Note this Github repo I linked to in the first post is what I'm using for the tests.
https://github.com/christoferd/test-te-li-july-2023

**Comment by juujisai** [comment]
You won't be able to access defined in app.js variables / imports in a browsers dev tools.

If your console logs inside app.js shows the code so it should be working fine. Does anything show on your local server? Did you try other components?

Other things to check:
- that `await import...` won't do anything unless you define an async function (I only checked the app.js file)
- try initializing the component via Javascript (`new Offcanvas(offcanvasEl)`)
- use `initTE` method inside the DOMContentLoaded event (`addEventListener("DOMContentLoaded", (event) => { initTE({Offcanvas}) });`)
- did you try putting `initTE` inside `setTimeout` ? Just to check whether it works after some `x` time

**Comment by christoferd** [comment]
@juujisai Thanks, but...

1- When removing "await" I get an error, when using "await import" I do not.
![image](https://github.com/mdbootstrap/Tailwind-Elements/assets/1835883/b82e7ffb-8313-4dea-a9bc-d7c7c0881d7d)

2- That is what I did with the buttons, but Offcanvas is not defined, not an object or anything. Console log Offcanvas fails.

3- "use initTE method inside the DOMContentLoaded event" ... error
![image](https://github.com/mdbootstrap/Tailwind-Elements/assets/1835883/0b537df2-306d-4036-bb40-fe3c43839db2)
![image](https://github.com/mdbootstrap/Tailwind-Elements/assets/1835883/c6742827-c7fe-419b-805e-35084d512555)

4- "initTE inside setTimeout" ... error
![image](https://github.com/mdbootstrap/Tailwind-Elements/assets/1835883/48d5fa77-e76b-4ee6-9fa0-99dbf4fc33af)
![image](https://github.com/mdbootstrap/Tailwind-Elements/assets/1835883/ff4e0465-3580-4622-adb4-17c8f5b7a821)

FYI Vite is compiling fine
![image](https://github.com/mdbootstrap/Tailwind-Elements/assets/1835883/821c702c-b2de-4adc-b7c0-4f13f77c0f23)

**Comment by christoferd** [comment]
Fiiiinaaaaalyyyyy fixed the issue.

I don't know why but the variables/consts in app.js need to be set to **_window_** scope...

![image](https://github.com/mdbootstrap/Tailwind-Elements/assets/1835883/92abdab8-1677-47a9-a676-8a73b4c406b4)

Note: I got the idea from [this guide](https://github.com/laravel/vite-plugin/blob/main/UPGRADE.md#migrating-from-vite-to-laravel-mix) where they specifically set Vapor objects to _window_ level scope.

Can see in and test with the repo linked in the original post.

**Comment by christoferd** [comment]
Closing because it's solved.
Please consider testing the repo and see how the solution fixes the problem.
Then perhaps update the documentation for Laravel integration, or Vite integration, or add to a Troubleshooting.
