### ISSUE TITLE
[Inline Timepicker with 12h] [Unable to change  time in Inline Timepicker]

### ISSUE THREAD

**Issue by Rishavraaj** [mdbootstrap/TW-Elements#1842]
**Describe the bug**

**To Reproduce**

1. I  setup the `inline time picker for 12 hrs` for Next JS by using the tailwind element documentation.
2. I added necessary file required to the tailwind.config file
3. I created a component called `NewTimePicker` in my next JS component folder by using export default 
4. In `NewTimePicker` component i user `useEffect` in `useEffect` i wrote the in `init` function in this i am importing the `Timepicker`, `Input` & `initTE` from the `tw-elements`
5. after importing these files i initialising the `timepicker` & `Input`  using `initTE`
6. after that i am targeting the main `div` with the `useRef` and creating a new `TimePicker`, after that i am calling the `init()` function
7. then i am importing my `NewTimePicker` component where i want to use like that:-

```
const NewTimePicker = dynamic(() => import("../components/NewTimePicker"), {
  ssr: false,
});
```
8. After doing that all steps i when i go and try to click on `clock` icon then the `inline time picker` is opening with `12 hours format` but when i try to change time then it's not allowing me to do that.

**Expected behavior**
I want to when user clicked on the clock icon then user should able to change the time using `Inline timepicker`

**Actual behavior**
When user clicked on the clock icon then user is not able to change the time in `time picker` its only showing `21:21  AM/PM ok` 

**Show your code**
It will be easier for us to help you if you [create a snippet using TE playground](https://tailwind-elements.com/snippets/) and include a link to it in your issue.

Here is my Time picker component code 

```
"use client";
import React from "react";
import { useEffect, useRef } from "react";

const NewTimePicker = () => {
  const pickerRef = useRef(null);
  useEffect(() => {
    const init = async () => {
      const { Timepicker, Input, initTE } = await import("tw-elements");
      initTE({ Timepicker, Input });
      const test = pickerRef.current;
      const newTimePicker = new Timepicker(test, {
        format12: true,
        inline: true,
      });
    };
    init();
  }, []);
  return (
    <div
      className="relative"
      id="timepicker-inline-12"
      ref={pickerRef}
      data-te-input-wrapper-init>
      <input
        type="text"
        className="peer block min-h-[auto] w-full rounded border-0 bg-transparent px-3 py-[0.32rem] leading-[1.6] outline-none transition-all duration-200 ease-linear focus:placeholder:opacity-100 peer-focus:text-primary data-[te-input-state-active]:placeholder:opacity-100 motion-reduce:transition-none dark:text-neutral-200 dark:placeholder:text-neutral-200 dark:peer-focus:text-primary [&:not([data-te-input-placeholder-active])]:placeholder:opacity-0"
        id="form2"
      />
      <label
        htmlFor="form2"
        className="pointer-events-none absolute left-3 top-0 mb-0 max-w-[90%] origin-[0_0] truncate pt-[0.37rem] leading-[1.6] text-neutral-500 transition-all duration-200 ease-out peer-focus:-translate-y-[0.9rem] peer-focus:scale-[0.8] peer-focus:text-primary peer-data-[te-input-state-active]:-translate-y-[0.9rem] peer-data-[te-input-state-active]:scale-[0.8] motion-reduce:transition-none dark:text-neutral-200 dark:peer-focus:text-primary">
        Select a time
      </label>
    </div>
  );
};

export default NewTimePicker;

```

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Make sure it is indeed an issue/bug report**

- If it's a general support question (you just can't figure out how something works), but not an issue with the UI Kit or documentation itself it's better to ask here:
  https://github.com/mdbootstrap/Tailwind-Elements/discussions/categories/support-from-community
- If it's an idea for a new feature, but you cannot write the code for it yourself, it's better to ask here:
  https://github.com/mdbootstrap/Tailwind-Elements/discussions/categories/share-ideas-request-features
- If it's general feedback, it's better to post it here:
  https://github.com/mdbootstrap/Tailwind-Elements/discussions/categories/kind-words-general-feedback

**Comment by juujisai** [comment]
Hi! I tried to use this timepicker in next and chaning time worked for me. What didn't work was the color of arrows that allow to change the time, maybe you have the same issue. The arrows are hardly visible right now. If it's the case then for now you could fix it like this:

```
      const newTimePicker = new Timepicker(
        test,
        {
          format12: true,
          inline: true,
        },
        {
          timepickerInlineIconUp:
            "absolute text-white -top-[35px] opacity-0 hover:opacity-100 transition-all duration-200 ease-[ease] cursor-pointer -translate-x-1/2 -translate-y-1/2 left-1/2 w-[30px] h-[30px] flex justify-center items-center",
          timepickerInlineIconDown:
            "absolute text-white -bottom-[47px] opacity-0 hover:opacity-100 transition-all duration-200 ease-[ease] cursor-pointer -translate-x-1/2 -translate-y-1/2 left-1/2 w-[30px] h-[30px] flex justify-center items-center",
        }
      );
```

We are going to fix them in the next release. I can also see the arrows are changing time really fast so we will have a look at this aswell.

**Comment by Rishavraaj** [comment]
@juujisai its not related to the button, It is working but randomly sometimes on refresh, it gets stuck to a static value. can you also add the implementation for inline time picker in docs,

**Comment by juujisai** [comment]
@Rishavraaj Maybe useEffect is making the timepicker beeing created more than once? If that would be the case, simple flag would remove this problem. Something like `!alreadyInited && init()`

As of the implementation, we have this section here: https://tailwind-elements.com/docs/standard/forms/timepicker/#section-inline-12

Or did you mean something else?

**Comment by Rishavraaj** [comment]
thanks @juujisai
