### ISSUE TITLE
Docs Bug / Question - Select Component - "Additional" CSS Classes

### ISSUE THREAD

**Issue by Routhinator** [mdbootstrap/TW-Elements#1866]
What does this part of the Select component doc mean? The sentence is not clear enough to understand what is meant exactly by "in order to use additional CSS classes" and the code doesn't match the statement... there is no div nor are there classes of any kind...

![Screenshot from 2023-08-15 19-18-03](https://github.com/mdbootstrap/Tailwind-Elements/assets/727535/be431cbc-2866-4f7e-9884-d7d182eaf1d6)

**Comment by juujisai** [comment]
I see this must have been removed by mistake. We will fix this soon. The snippet should look like this:
```
      <div class="shadow-xl">
        <select data-te-select-init>
          <option value="1">One</option>
          <option value="2">Two</option>
          <option value="3">Three</option>
          <option value="4">Four</option>
          <option value="5">Five</option>
          <option value="6">Six</option>
          <option value="7">Seven</option>
          <option value="8">Eight</option>
        </select>
        <label data-te-select-label-ref>Example label</label>
      </div>
```    

To make our select work, we are creating a new element based on the native select. When there are classes added to the wrapper (shadow for example), they will be transfered to the wrapper of this new element. You can check it in the inspect tool of your browser. I hope that helps a bit

**Comment by Routhinator** [comment]
Thanks for that. That helps.
