### ISSUE TITLE
[Navbar] The dropdown menu under the navbar gets off-viewport on mobile

### ISSUE THREAD

**Issue by jcornil** [mdbootstrap/TW-Elements#1877]
**Describe the bug**
The dropdown menu under the navbar gets off-viewport on mobile like the screenshot.

**To Reproduce**

1. Navigate to 'Navbar Component page'
2. Click on 'hamburger menu' under the Basic Example.
3. Click on 'Alarm or Profile icon' to open a dropdown menu.

**Expected behavior**
The dropdown menu appears in the viewport.

**Actual behavior**
The half of the dropdown menu appears outside the viewport.

**Desktop (please complete the following information):**
- OS: Windows 11 22H2
- Browser Chrome 116.0.5845.97, Firefox 116.0.3

**Smartphone (please complete the following information):**
- Device: iPhone XS max
- OS: iOS 16.6
- Browser Safari

**Additional context**
![K-20230818-181123120](https://github.com/mdbootstrap/Tailwind-Elements/assets/157859/7868ad39-28a9-4b41-a098-a919c51d7ec6)

**Comment by iprzybysz** [comment]
Thanks for reporting this bug. We'll fix it as soon as possible. At the moment, a workaround for this problem may be to change classes `left/right` depending on your needs in the `dropdown-menu` element.

**Comment by iprzybysz** [comment]
We identified this problem - deleting `data-te-navbar-ref` attribute from `nav` element and `left-auto right-0` classes from `drodpown-menu` element should fix this issue.

**Comment by jcornil** [comment]
> We identified this problem - deleting `data-te-navbar-ref` attribute from `nav` element and `left-auto right-0` classes from `drodpown-menu` element should fix this issue.

Yeah, it fixed the issue. Thanks for fast response.
