### ISSUE TITLE
Select element and  dynamic value (setValue)

### ISSUE THREAD

**Issue by wojciechkibitlewski** [mdbootstrap/TW-Elements#1878]
Hi,
I have some problems with the Select element (Laravel)
When I use this;

window.Select = Select
const singleSelect = document.getElementById('category_id');
const singleSelectInstance = window.Select.getInstance(singleSelect);
singleSelectInstance.setValue("1");
        
In the tailwind-element.js file it all works.
However, I need to pass a dynamic value (from the database) to setValue.

How can I do this? No way works.

**Comment by juujisai** [comment]
Hi, calling the `setValue` method after you receive your data from the api call doesn't work? For example 
```
import axios from "axios";

axios.get('/api/data')
    .then(response => {
        ...
        singleSelectInstance.setValue("1");
        ...
    })
    .catch(error => {
        console.error(error);
    });
```

I have a question aswell. Why do you need to add the component to the window object? Does it not work for you when you use it with our `te` object?

**Comment by wojciechkibitlewski** [comment]
I use Blade Templates. 

In the end, I gave up on the component. I used the standard syntax for select input and used if - else.
