### ISSUE TITLE
Multiple Select Components Not Initializing Properly in React

### ISSUE THREAD

**Issue by garryInWeb** [mdbootstrap/TW-Elements#1880]
---

**Describe the bug**
When creating a React project using the Tailwind Elements library, I followed the [React Integration Guide](https://tailwind-elements.com/docs/standard/integrations/react-integration/) to create a Select component within a `Component` component. I then created two instances of the `Component` component on a page. However, only the first Select component's style is applied, and the subsequent Select components are not styled properly.

**To Reproduce**

1. Create a React project following the [React Integration Guide](https://tailwind-elements.com/docs/standard/integrations/react-integration/).
2. Create a Select component within a `Component` component.
3. Add two instances of the `Component` component to a single page.
4. Observe that only the first Select component's style is applied.

**Expected behavior**
All Select components on the page should be styled properly according to the Tailwind Elements library.

**Actual behavior**
Only the first Select component on the page is styled properly. Subsequent Select components are not styled.

**Show your code**
You can find the code for this issue in my [GitHub repository](https://github.com/garryInWeb/tw-essential.git).

**Desktop (please complete the following information):**

- OS: MAC
- Browser: Chrome

**Additional context**
This issue seems to be related to the initialization of multiple Select components within multiple instances of a parent component on a single page.

**Make sure it is indeed an issue/bug report**
This is indeed a bug report related to the UI Kit and its integration with React.

---

**Comment by juujisai** [comment]
Hi! Try using the `initTE( { Select } )` method inside their parent component. I've created a new app, new component with only select template inside and called the `initTE` method inside `App.jsx`. The two Select components were working fine for me.

You can also try to init the select via JS, for example:
```
const selectEl = document.getElementById('mySelect');
const select = new Select(selectEl);
```

Hope it helps!

**Comment by garryInWeb** [comment]
Thank you for your suggestions! I tried using initTE({Select}) in my sample App.js, and it worked successfully. However, it didn't work in my main project. Fortunately, I was able to resolve the issue by using the new Select approach you provided.
