### ISSUE TITLE
Old version documentation

### ISSUE THREAD

**Issue by Ischafak** [mdbootstrap/TW-Elements#1922]
It is not a issue but i dont know where to write you. I am using 1.0.0-alpha12 right now. 
Is it possible for me to access old documentation?

**Comment by juujisai** [comment]
Hi, checkout this tutorial on how to open our docs localy

https://tailwind-elements.com/docs/standard/getting-started/local-installation/

**Comment by Ischafak** [comment]
ok thank you so much

**Comment by jcalfee** [comment]
Please consider having static docs and just making those available online.  Thank you.
