### ISSUE TITLE
[Validation] [twe reports supplied function is not defined]

### ISSUE THREAD

**Issue by ahrizonaa** [mdbootstrap/TW-Elements#1926]
**Describe the bug**
TWE Validation warns that my custom validation rule does not exist during every call facilitated by `<form data-te-active-validation="true">...</form>`

**To Reproduce**

1. Implement a custom rule in JS using the exact same method given in TWE's documentation:  https://tailwind-elements.com/docs/standard/forms/validation/#custom-validation
2. Bind the validation to html input field i.e. `textarea`.
3. Ensure enclosing form has attribute `data-te-active-validation="true"`.
4. While viewing web app in browser, open chrome dev tools.
5. Start type in input field.
6. View the console.warn message after every `keyup` stating `Rule 'myCustomRule' does not exist`.

**Expected behavior**
Expected behavior is that the twe validation component accurately reports when my supplied validation function is defined or not.

**Actual behavior**
twe validation component is reporting that custom validation rule does not exist, when in reality it does exist and its being used properly.

**Show your code**
*I could not figure out how to import individual components in the snippet playground*
```
<body>
  <form data-te-validation-init data-te-validated="false" data-te-active-validation="true" id="form-id">
    <div class="relative" data-te-input-wrapper-init data-te-validate="input" data-te-validation-ruleset="isValid" >
      <textarea id="textareaId"></textarea>
    </div>
  </form>
  <script type="module">
    import { Input, Validation, initTE } from 'tw-elements';
    initTE({ Input, Validation });
    
    function isValid(val,msg,str) {
      return 'no';
    }
    
    let config = {
      customErrorMessages: { isValid: 'maybe' },
      customRules: { isValid: isValid }  // tried isValid: (val,msg,str) => { ... }; isValid: function(val,msg,str) { ... }; fn.bind(...) ...
    }
    
    new Validation(document.getElementById('form-id', config))
    
    // start typing into textarea, twe will output something like such:
    // console.warn('Rule isValid does not exist.')
  </script>
</body>
```

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Chrome
- Version: 116.0.5845.180

**Additional context**
The end result is that the validation still correctly validates my input element using given custom rule function.  I've tried every different combination of function declaration i.e. (`function func() {}` in enclosing scope, inline `function() {}`, inline lambda, fn defined on class and passing its prop name), and using bind i.e. `.bind(this, that, ...)` on each one.  I get the same results in every scenario.

- If it's a general support question (you just can't figure out how something works), but not an issue with the UI Kit or documentation itself it's better to ask here:
  https://github.com/mdbootstrap/Tailwind-Elements/discussions/categories/support-from-community
- If it's an idea for a new feature, but you cannot write the code for it yourself, it's better to ask here:
  https://github.com/mdbootstrap/Tailwind-Elements/discussions/categories/share-ideas-request-features
- If it's general feedback, it's better to post it here:
  https://github.com/mdbootstrap/Tailwind-Elements/discussions/categories/kind-words-general-feedback

**Comment by ahrizonaa** [comment]
I remembered the reason why this matters xD.  I'm trying to use the callback for when form validation fails, during the active typing validation, so I can set us that info to update the state of other html elements.  I've added event listeners to the 'invalid.te.validation' event, its only fired after clicking submit, not during active typing input.  However active typing is validation and updating the dom correctly.  Maybe that event is not supported during active typing, I initially thought it was related to the 'custom rule not found' message

**Comment by juujisai** [comment]
Hi!

It looks like the issue is inside the `config` you are providing. The `customRules` options need an object with named method (the same for the error message). You can checkout this example, how we are adding a new custom rule to the rule set:

![image](https://github.com/mdbootstrap/Tailwind-Elements/assets/52455076/facfdb08-9c84-4cb1-9e5e-0e82d5be4128)

https://tailwind-elements.com/docs/standard/forms/validation/#custom-validation



As of the event for active validation, `changed.te.validation` should fire everytime input's value changed. Check how it works in this example:
https://tailwind-elements.com/docs/standard/forms/validation/#validation-with-tooltips

**Comment by ahrizonaa** [comment]
@juujisai I believe thats exactly what I'm doing, and thats what I showed in my snippet.  The name of my customRule is **isValid**.  The config object I'm passing has `customRules.isValid`

as described in my snippet as well:
```
    let config = {
      customErrorMessages: { isValid: 'maybe' },
      customRules: { isValid: isValid }  // tried isValid: (val,msg,str) => { ... }; isValid: function(val,msg,str) { ... }; fn.bind(...) ...
    }
    
    new Validation(document.getElementById('form-id', config))
```

**Comment by ahrizonaa** [comment]
screenshot for clarify

![image](https://github.com/mdbootstrap/Tailwind-Elements/assets/99224230/24d27609-176d-460f-9fee-8343cd58017d)

**Comment by ahrizonaa** [comment]
it is actually using the function `isValid` that I provided in the config.  Its just reporting that it's not defined, before and after successfully using it

**Comment by juujisai** [comment]
Ok I see what may cause the problem. You are initializing the `validation` component twice, and the first time, the validation doesn't see the `isValid` method. You are initializing once with data attribute `data-te-validation-init` and then again with use of JS `new Validation(...)`. The second one has the ruleset `isValid` added as an option and the first one does not. 

Try removing the `data-te-validation-init` data attribute and then check if it works like you want to.

**Comment by ahrizonaa** [comment]
yes haha that solves it and answers why my validation always ran twice at a time xD
