### ISSUE TITLE
sidenav import nuxt3

### ISSUE THREAD

**Issue by Ischafak** [mdbootstrap/TW-Elements#1934]
First of all hi and thank you for your work.
I am using nuxt3 with ssr and i am trying to implement your sidenav to my project.

<img width="565" alt="image" src="https://github.com/mdbootstrap/Tailwind-Elements/assets/13226879/0bc4db54-3ee1-4abd-9f4a-87070baf0923">
when i do something like this i cant access sidenav at the bottom method. When i try to import sidenav before mounted it gives me error something like "document not found because of ssr" 

can anyone help me how can i solve this?

**Comment by juujisai** [comment]
Hi, I think the issue here is that the `Sidenav` is beeing imported inside the `onMounted` hook, and the `changeToggle` method doesn't have access to the component. You can try adding a new variable and calling the `getInstance` method on that variable, like here:
```
<script setup>
import { onMounted } from "vue";
let SidenavComponent;

onMounted(async () => {
  const { Sidenav, initTE } = await import("tw-elements");
  initTE({ Sidenav });
  SidenavComponent = Sidenav;
});

const changeToggle = () => {
  const instance = SidenavComponent.getInstance(
    document.getElementById("sidenav-4")
  );
  instance.toggleSlim();
};
</script>
```

Hope it helps!

**Comment by Ischafak** [comment]
it works very well thank you so much you are a saviour. If it is possible for me to ask 2 more question i want to ask you this. 
for slim version of this page https://tailwind-elements.com/docs/standard/navigation/sidenav/#docsTabsOverview

i didnt understand how sidenav expands when i click dropdown menus at left side also is it possible for me to disable that?
and when i click dropdown that 3 line icon button goes on focus i guess it changes color can i fix that?
<img width="231" alt="image" src="https://github.com/mdbootstrap/Tailwind-Elements/assets/13226879/2170d847-f9e0-4753-b590-f3c1b87b7f63">

**Comment by juujisai** [comment]
You can remove the `focus` classes from the button and it won't change color then. Remove or change those classes `focus:bg-primary-700 focus:shadow-lg focus:outline-none focus:ring-0`

As of the expanding of the sidenav after menu click, try changing the classes and attributes of the `nav` element. 
```
  <nav
    id="sidenav-4"
    class="fixed left-0 top-0 z-[1035] h-screen w-60 -translate-x-full overflow-hidden bg-white shadow-[0_4px_12px_0_rgba(0,0,0,0.07),_0_2px_4px_rgba(0,0,0,0.05)] data-[te-sidenav-hidden='false']:translate-x-0 dark:bg-zinc-800"
    data-te-sidenav-init
    data-te-sidenav-hidden="false"
    data-te-sidenav-mode="side"
    data-te-sidenav-content="#slim-content"
  >
```

Don't add the slim attributes and classes to the nav element, leave only the `data-te-sidenav-slim="false"` added to the sidenav links, and the `toggleSlim` method.

**Comment by Ischafak** [comment]
ok i will try that thank you so much you are the best.

lastly for sidenav if you give us the possibility that add static backdrop like modal would be very cool. I checked the api but didnt saw that

**Comment by juujisai** [comment]
@Ischafak Thanks, we will keep that in mind
