### ISSUE TITLE
Datepicker cannot be close

### ISSUE THREAD

**Issue by hellyanggara** [mdbootstrap/TW-Elements#1940]
Hi, I'm using laravel breeze with inertia and vue package

I've been using Timepicker and its working fine

My Timepicker Component as show below 
```
<template>
    <div
        data-te-with-icon="false"
        data-te-timepicker-init
        data-te-format24="true">
        <input 
            :value="modelValue" @input="$emit('update:modelValue', $event.target.value)"
            class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"
            type="text"
            data-te-toggle="timepicker" />
    </div>
</template>
<script setup>
import { onMounted } from "vue";
import { Timepicker, Input, initTE } from "tw-elements";

onMounted(() => {
    initTE({ Timepicker, Input }, { allowReinits: true });
});

defineProps(['modelValue']);

defineEmits(['update:modelValue']);

</script>
```

as shown below, I'm using Timepicker for "start_time", and Datepicker for "start_date"
v-model for both is working fine,
but in datepicker, when I click outside or click "OK" or "Cancel", datepicker won't be close but the date I pick is send to input, the problem is it wont close and the selected date also doesnt have bacground blue color.

![err](https://github.com/mdbootstrap/Tailwind-Elements/assets/61726564/55319d9e-eda9-4756-99f8-253a8e3f761f)

My Datepicker Component as shown below
```
<template>
    <div
      class="relative mb-3"
      data-te-datepicker-init
      data-te-input-wrapper-init>
      <input
        type="text"
        data-te-datepicker-toggle-ref
        data-te-datepicker-toggle-button-ref
        :value="modelValue" @input="$emit('update:modelValue', $event.target.value)"
        class="peer block min-h-[auto] w-full rounded border-0 bg-transparent px-3 py-[0.32rem] leading-[1.6] outline-none transition-all duration-200 ease-linear focus:placeholder:opacity-100 peer-focus:text-primary data-[te-input-state-active]:placeholder:opacity-100 motion-reduce:transition-none dark:text-neutral-200 dark:placeholder:text-neutral-200 dark:peer-focus:text-primary [&:not([data-te-input-placeholder-active])]:placeholder:opacity-0"
        placeholder="Select a date" />
      <label
        for="floatingInput"
        class="pointer-events-none absolute left-3 top-0 mb-0 max-w-[90%] origin-[0_0] truncate pt-[0.37rem] leading-[1.6] text-neutral-500 transition-all duration-200 ease-out peer-focus:-translate-y-[0.9rem] peer-focus:scale-[0.8] peer-focus:text-primary peer-data-[te-input-state-active]:-translate-y-[0.9rem] peer-data-[te-input-state-active]:scale-[0.8] motion-reduce:transition-none dark:text-neutral-200 dark:peer-focus:text-primary"
        >Select a date</label
      >
    </div>
</template>
<script setup>
import { onMounted } from "vue";
import { Datepicker, Input, initTE } from "tw-elements";

onMounted(() => {
    initTE({ Datepicker, Input }, { allowReinits: true, });
});

defineProps(['modelValue']);

defineEmits(['update:modelValue']);

</script>
```

**Comment by juujisai** [comment]
Hi! Most of the issues with datepicker not wanting to close were caused when the datepicker was initialized more than once. Maybe try setting some guard inside the onMounted hook and see if that changes anything. Please check the routing after doing so
```
onMounted(() => {
if (!wasInitialized) {
    initTE({ Datepicker, Input }, { allowReinits: true, });
    wasInitialized.value = true;
 }
});
```

**Comment by hellyanggara** [comment]
> Hi! Most of the issues with datepicker not wanting to close were caused when the datepicker was initialized more than once. Maybe try setting some guard inside the onMounted hook and see if that changes anything. Please check the routing after doing so
> 
> ```
> onMounted(() => {
> if (!wasInitialized) {
>     initTE({ Datepicker, Input }, { allowReinits: true, });
>     wasInitialized.value = true;
>  }
> });
> ```

thx for your reply, 
silly me,
I accidentally found the problem..
It was my friend who change plugins inside tailwindconfig.js
he write 
`plugins: [require('@tailwindcss/forms','tw-elements/dist/plugin.cjs')],`

and I change it into
`
    plugins: [
        require('@tailwindcss/forms'),
        require('tw-elements/dist/plugin.cjs')
    ],
`

but why time picker work in both?
but datepicker already work now..
