### ISSUE TITLE
Datetimepicker - timepicker options are not provided correctly

### ISSUE THREAD

**Issue by juujisai** [mdbootstrap/TW-Elements#1947]
Related Issue: https://github.com/mdbootstrap/Tailwind-Elements/issues/1943

Bug most likely is here: https://github.com/mdbootstrap/Tailwind-Elements/blob/master/src/js/forms/dateTimepicker/index.js#L284

**Comment by theCephas** [comment]
Hello there! Please assign me this task!

**Comment by juujisai** [comment]
Hi @theCephas. Thanks for you help, I'm adding you to this task.

We require our contributors to sign the CLA before we check and merge any Pull Request. See:
https://cla.tailwind-elements.com/

Make sure to checkout the Contribute guide:
https://tw-elements.com/docs/standard/getting-started/contribute/

**Comment by juujisai** [comment]
Hello @theCephas, were you able to start working on the task?

**Comment by juujisai** [comment]
Hi, @theCephas. I assigned myself to the task so we can keep things moving.  If you would like to help with any other issue, let me know.
