### ISSUE TITLE
Update default text color to #4f4f4f

### ISSUE THREAD

**Issue by juujisai** [mdbootstrap/TW-Elements#1949]

**Comment by shubhalgupta** [comment]
which files needs to be changed?

**Comment by juujisai** [comment]
Hi @shubhalgupta . Most likely the scss files in the `scss` folder and `site/...` . We'll update the colors for the 2.0.0 version

**Comment by shubhalgupta** [comment]
@juujisai where in the site folder? Can you please elaborate

**Comment by shubhalgupta** [comment]
I think in main.css file, right?

**Comment by shubhalgupta** [comment]
please assign me this issue!

**Comment by juujisai** [comment]
I've assigned you to this task. As I said before, the change will have to wait for the 2.0.0 release.

**Comment by shubhalgupta** [comment]
@juujisai please review this!
