### ISSUE TITLE
Charts - examples are squished on mobile view

### ISSUE THREAD

**Issue by juujisai** [mdbootstrap/TW-Elements#1982]

**Comment by njolipatrick** [comment]
I am interested in contributing towards fixing this issues @juujisai can you please prrovide context as to what examples are affected?

**Comment by juujisai** [comment]
Each example that has charts inside them have to be updated so that they wont look that squished.
![image](https://github.com/mdbootstrap/TW-Elements/assets/52455076/a61bdc92-8f21-4e3a-98c1-ff59af4a0f1d)
 
Im thinking about those pages:
https://tw-elements.com/docs/standard/data/charts/
https://tw-elements.com/docs/standard/data/charts-advanced/

If you want to try and fix this, please checkout the contribute guide: https://tw-elements.com/docs/standard/getting-started/contribute/

Our documentation is beeing made with `hugo` so it would be best if use it aswell so that you could see the changes you made. Also this change needs to be made from the `docs` branch and into the `docs` branch.

Let me know if you still want to do this.

**Comment by marameref** [comment]
Is this issue still open, can i go ahead and work on it?

**Comment by juujisai** [comment]
@marameref if @njolipatrick doesn't answer back then I'll assign this to you. I'll get back with that to you.

Did you use hugo before? Did you try to open our documentation localy?

**Comment by njolipatrick** [comment]
@juujisai Yes i still want to do this fix

**Comment by juujisai** [comment]
@njolipatrick Okay go for it. Remember to change it on the `docs` branch

**Comment by njolipatrick** [comment]
@juujisai i have encounter severally issues while setting the docs and master branch up.
1. On initial setup using the instruction from [this](https://tw-elements.com/docs/standard/getting-started/contribute/) i am presented with this error
![image](https://github.com/mdbootstrap/TW-Elements/assets/36375033/ec920026-9580-4ab4-ae67-159c12ab33cd)
The only way i can get passed it is to remove all instance where footer ( {{ partial "footer/footer.html" . }}, {{ partial "footer/footer-scripts.html" . }}, {{ partial "footer/footer-docs.html" . }} ) was call through the template.

2. I removed all that was mentioned in 1. and the code ran but now the charts where not showing.
![image](https://github.com/mdbootstrap/TW-Elements/assets/36375033/fc9cadae-0030-4a8a-853b-9ca4706e74a8)

3.And the Javascripts are not working also so the dropdown and toggles and not working on the entire application.
![image](https://github.com/mdbootstrap/TW-Elements/assets/36375033/71076295-112c-4d3d-a595-604a5e42cf97)

I have hugo extended installed.
I followed the the instruction listed on the [Documentation contributions](https://tw-elements.com/docs/standard/getting-started/contribute/) If i am missing an extra step please let me know. I am running on a windows 10.

**Comment by juujisai** [comment]
1. Maybe the hugo version is the problem here. I'm working on v0.106.0. But as log as the docs open it should be fine, just don't push the changes with removed code 😄 
2. / 3. Did you try to run `npm run build` before opening docs? 

I'll leave here our guide for local installation. Maybe it would be useful
https://tw-elements.com/docs/standard/getting-started/local-installation/

**Comment by njolipatrick** [comment]
> 1. Maybe the hugo version is the problem here. I'm working on v0.106.0. But as log as the docs open it should be fine, just don't push the changes with removed code 😄 
> 
> 2. / 3. Did you try to run `npm run build` before opening docs? 
> 
> 
> 
> I'll leave here our guide for local installation. Maybe it would be useful
> 
> https://tw-elements.com/docs/standard/getting-started/local-installation/

😌Of course I will not push with deleted code. Will revert those changes before I push.

Yes I did run the build command at some point. It is also a part of the doc:install script too.

Followed the instructions on https://tw-elements.com/docs/standard/getting-started/local-installation/

Will also install your version number of Hugo.

**Comment by njolipatrick** [comment]
@juujisai the issues was with my version of hugo. Thank you for the support. I think the project may need to move toward being compatible with the latest version of hugo asap.

I will work on the neccesary changes now.

**Comment by njolipatrick** [comment]
@juujisai 
Before 
![image](https://github.com/mdbootstrap/TW-Elements/assets/36375033/db71faaa-928e-4245-9792-dc9668262f1a)

After
![image](https://github.com/mdbootstrap/TW-Elements/assets/36375033/a1292929-0c2f-4cf9-9900-0d74fcd4c9f8)

This looks good yeah?

**Comment by njolipatrick** [comment]
@juujisai i have submitted a PR to this issues https://github.com/mdbootstrap/TW-Elements/pull/2007

**Comment by juujisai** [comment]
@njolipatrick thank you, I'll review it when I have some time. From what I can see now though, we can't make changes in this file `site/layouts/shortcodes/twsnippet/demo.html` because it will change other demos aswell and we don't want that. It would be best to only change styling on the charts pages

**Comment by njolipatrick** [comment]
Cool, Let me remove the change i made on the demo.html file then and update my PR @juujisai

**Comment by juujisai** [comment]
Fixed: 

1. https://github.com/mdbootstrap/TW-Elements/pull/2007
2. https://github.com/mdbootstrap/TW-Elements/commit/a06fac96cd9dbd11d0376efa358460b44e172250
