### ISSUE TITLE
[Rating] [`dispose()` method throws an error]

### ISSUE THREAD

**Issue by Nikitossik** [mdbootstrap/TW-Elements#2006]
**Describe the bug**
I have an instance of the Rating component. When I call dispose(), the error occurs: 
![image](https://github.com/mdbootstrap/TW-Elements/assets/55406009/229ad737-31c2-440b-ba10-d6846543d3d5)

**Show your code**
There is an Internal server error when I try to add a playgound, so this is my code:
`import { Rating, initTE } from "tw-elements";`

`initTE({
    Rating
});`

`const diffRatingEl = document.getElementById('difficulty-rating');`

`let diffRating = new Rating(diffRatingEl);`
`diffRating.dispose();`

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome
- Version: 118.0.5993.70

**Additional context**
I looked up the code of rating in `node_modules\tw-elements\dist\src\js\components\rating.js`: 
` this._icons.removeAttribute("tabIndex");`
this._icons prop is supposed to be an array, so it's obvious that removeAttribute() is not a function, instead we should run this on every icon: 
`this._icons.forEach(el => el.removeAttribute("tabIndex"));`

**Comment by juujisai** [comment]
Unfortunately this is a bug. I'm adding this issue to our project to-fix list. Thank you for letting us know
