### ISSUE TITLE
[tooltip] [How to customize tooltip style]

### ISSUE THREAD

**Issue by RabbiIslamRony** [mdbootstrap/TW-Elements#2011]
**Describe the Improvement **

I am using only the Tailwind CSS CDN in our HTML project, but I cannot figure out how to customize this tooltip. It's really hard to understand for a beginner. I believe there is a way to apply styles, but I cannot find it.

**Show your code**
I applied two methods, but they are not working on my end either
1/ https://prnt.sc/ZueYfRG28-Kw
2/ https://prnt.sc/lN23kofh26ol

**Desktop (please complete the following information):**
- Window: [e.g. iOS]
- chrome [e.g. chrome, safari]

**Comment by iprzybysz** [comment]
Hi, if you want to customize tooltip, you have to add your own template by using `data-te-template` attribute.

Here is the example:

```
<p>
   Hover the link to see the
   <a
      href="#"
      class="transititext-primary text-primary transition duration-150 ease-in-out hover:text-primary-600 focus:text-primary-600 active:text-primary-700 dark:text-primary-400 dark:hover:text-primary-500 dark:focus:text-primary-500 dark:active:text-primary-600"
      data-te-toggle="tooltip"
      title="Hi! I'm tooltip"
      data-te-template='<div class="opacity-0 transition-opacity duration-300 ease-in-out absolute z-[1080] block m-0 text-sm not-italic font-normal text-left no-underline underline-offset-auto normal-case leading-6 tracking-normal break-normal whitespace-normal" role="tooltip">
                          <div data-te-tooltip-inner-ref class="tooltip-inner max-w-[200px] text-sm py-1.5 px-4 text-white text-center bg-[#6d6d6d] rounded"></div>
                        </div>'
      >tooltip</a>
</p>
```
