### ISSUE TITLE
Where is the component customization section in the documentation?

### ISSUE THREAD

**Issue by RabbiIslamRony** [mdbootstrap/TW-Elements#2013]
I tried to find a method for customizing components multiple times. I created issues on how to customize this component or element. If you know a valid location where all customizations are available, please refer to the link below. Thanks

**Comment by juujisai** [comment]
Most components have an `API` tab that contains options and classes that can be used for customization. For example: https://tw-elements.com/docs/standard/forms/datepicker/#docsTabsAPI

**Comment by RabbiIslamRony** [comment]
> Most components have an `API` tab that contains options and classes that can be used for customization. For example: https://tw-elements.com/docs/standard/forms/datepicker/#docsTabsAPI

Any video tutorial available to how to customize component classes, https://prnt.sc/2fR3iBaRl2eT
