### ISSUE TITLE
[Rating] [Usage of rating in svelte]

### ISSUE THREAD

**Issue by vongohren** [mdbootstrap/TW-Elements#2026]
**Describe the bug**
When using ratings in svelte, you first as mentioend before have to initiate the tw lib inside onMount.
But when you are navigating between multiple pages with rating on it

The data class function does not work. It seems not to want to initate on subsequent pages

For extra info, im using [tenstack tables](https://tanstack.com/table/v8/docs/examples/svelte/basic) and add rating as a column into that mix.

**To Reproduce**
Have a rating componet on subpages and navigate between them. They become inactive and not clickable or react to hoover.

**Expected behavior**
I expect data attribute to work after navigating to other pages.

Potentially update docs to reflect svelte support on components

**Actual behavior**
After navigating to another page, the rating elements dont react on click or hoover.

**Show your code**
```
<script>
  onMount(async () => {
    const { Rating, initTE } = await import('tw-elements');
    initTE({ Rating });

    const myRatingEl = document.getElementById(`${id}`)
    const instance = new Rating(myRatingEl, {});
    console.log(myRatingEl)
    myRatingEl.addEventListener('onSelect.te.rating', (e) => {
      console.log("snickser")
    })

    return () => {
      instance.dispose()
    }
  });
  </script>
  
  <ul id="{id}" class="my-1 flex list-none gap-1 p-0">
  <li>
    <span
      class="text-primary [&>svg]:h-5 [&>svg]:w-5"
      data-te-rating-icon-ref>
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 24 24"
        stroke-width="1.5"
        stroke="currentColor">
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z" />
      </svg>
    </span>
  </li>
  <li>
    <span
      class="text-primary [&>svg]:h-5 [&>svg]:w-5"
      data-te-rating-icon-ref>
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 24 24"
        stroke-width="1.5"
        stroke="currentColor">
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z" />
      </svg>
    </span>
  </li>
  </ul>
  
```

**Desktop (please complete the following information):**

- OS: Mac
- Browser Chrome
- Version 117.0.59

**Additional context**

**Comment by juujisai** [comment]
Hi! Try adding the `allowReinits` option. For example
```
initTE({ Rating }, { allowReinits: true });
```

Read more about `initTE` method here:
https://tw-elements.com/docs/standard/getting-started/quick-start/#formats

**Comment by vongohren** [comment]
Thanks for that pointer, that did do the trick!
