### ISSUE TITLE
Datatables - can not scroll the page while on the table

### ISSUE THREAD

**Issue by alkadoHs** [mdbootstrap/TW-Elements#2036]
**Scrolling the page while touching the datatable**
Datatables component has some issues and this is a big problem while I'm using my site on a small device.
When you're on the table you cannot scroll further down the page unless you touch out of the table to scroll it

Please fix this, I'm using this Library because datatables component 🙏

**Comment by iprzybysz** [comment]
Hi, I've just added it to our project board. We'll fix it as soon as possible.

**Comment by alkadoHs** [comment]
Thank you, glad  to hear 🙏
