### ISSUE TITLE
[Datepicker] set data attribute data-te-format to mmm-yyyy error value is undefined

### ISSUE THREAD

**Issue by AndoruKun** [mdbootstrap/TW-Elements#2052]
**Describe the bug**
I Create component datepicker with format MMM-YYYY first time on Date Change event got error on parseDate in plugins its say value `tw-elements.es.min.js:6093 Uncaught TypeError: Cannot read properties of undefined (reading 'value')` then it can't open again

**To Reproduce**
Simple just put dateFormat MMM-YYYYY
you cant try in playground 
[https://tw-elements.com/snippets/tailwind/andrew_lim/5751925#html-tab-view](url)
<img width="1680" alt="Screenshot 2023-10-31 at 14 49 45" src="https://github.com/mdbootstrap/TW-Elements/assets/25896815/ec10c3e4-f96f-4012-887a-19a26906124f">

**Comment by juujisai** [comment]
Hi! Seems like when we add a format without a day the picker is experiencing some issues. Thanks for reporting this bug

**Comment by juujisai** [comment]
Update: for now we won't support formats that do not contain the full data (days, months, years).
