### ISSUE TITLE
Issue with Creating 2D Bar Chart using tw-elements / Problème de création de diagramme en barres en 2D avec tw-elements

### ISSUE THREAD

**Issue by leknoppix** [mdbootstrap/TW-Elements#2061]
**ENGLISH**
I  want to express my heartfelt gratitude to the developers of tw-elements for sharing this valuable resource with the community.

**Issue**

I would like assistance in fixing the code to display a two-dimensional bar chart correctly, with data for years and the number of signed and unsigned articles.

**Current Code**

```html
<canvas
    data-te-chart="bar"
    data-te-dataset-label="Number of Articles"
    data-te-labels="['2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021']"
    data-te-dataset-data='[
                            {
                                "label": "Articles signés",
                                "data": [12, 19, 3, 5, 2, 3, 5, 2, 3],
                            },
                            {
                                "label": "Articles non signés",
                                "data": [22, 29, 15, 25, 20, 30, 25, 20, 15],
                            }
                        ]'
></canvas>
```

**Problem Description**

The above code should ideally generate a two-dimensional bar chart, but it is not functioning correctly. The data for signed and unsigned articles is not being correctly represented, and the bars are not displaying properly in the chart.

---
**FRENCH**
Je tiens également à remercier chaleureusement les développeurs de tw-elements pour avoir partagé cette ressource précieuse avec la communauté.

**Problème**

J'aimerais obtenir de l'aide pour corriger le code afin qu'il affiche un diagramme en barres en deux dimensions correctement, avec des données pour les années et le nombre d'articles signés et non signés. 

**Code actuel**

```html
<canvas
    data-te-chart="bar"
    data-te-dataset-label="Nombre d'articles"
    data-te-labels="['2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021']"
    data-te-dataset-data='[
                            {
                                "label": "Articles signés",
                                "data": [12, 19, 3, 5, 2, 3, 5, 2, 3],
                            },
                            {
                                "label": "Articles non signés",
                                "data": [22, 29, 15, 25, 20, 30, 25, 20, 15],
                            }
                        ]'
></canvas>
```

**résultat**
Le code ci-dessus devrait normalement générer un diagramme en barres en deux dimensions, mais il ne fonctionne pas correctement. Les données pour les articles signés et non signés ne sont pas correctement représentées, et les barres n'apparaissent pas correctement dans le graphique.

**Comment by juujisai** [comment]
Hi! When dealing with more advanced datasets it's better to initialize the Chart via JS, not via data attributes.

```
<canvas id="myChart"></canvas>

...

const dataChart = {
  type: "bar",
  data: {
    labels: [
      "2013",
      "2014",
      "2015",
      "2016",
      "2017",
      "2018",
      "2019",
      "2020",
      "2021",
    ],
    datasets: [
      {
        label: "Articles signés",
        data: [12, 19, 3, 5, 2, 3, 5, 2, 3],
      },
      {
        label: "Articles non signés",
        data: [22, 29, 15, 25, 20, 30, 25, 20, 15],
        backgroundColor: "#94DFD7",
        borderColor: "#94DFD7",
      },
    ],
  },
};

const optionsChart = {
  options: {
    scales: {
      y: {
        stacked: false,
        ticks: {
          beginAtZero: true,
        },
      },
      x: {
        stacked: false,
      },
    },
  },
};

new Chart(document.getElementById("myChart"), dataChart, optionsChart);

```

**Comment by leknoppix** [comment]
Thanks
