### ISSUE TITLE
 `Select` with search (filter) feature and add loading options from server. Not covered in the documentation.

### ISSUE THREAD

**Issue by MaciejZimoch** [mdbootstrap/TW-Elements#2095]
**Describe the bug**
From [our FB group](https://www.facebook.com/groups/682245759188413): we came across an issue when we want to use the `Select` with search (filter) feature and add loading options from server. But seems like this is not covered into the documentation [here](https://tw-elements.com/docs/standard/forms/select/). 
So, does anyone had similar experience? Any help will be appreciated!
![image](https://github.com/mdbootstrap/TW-Elements/assets/143814532/e955ff35-8e1e-41b8-a45c-a8a4a7151507)

**Comment by juujisai** [comment]
Hi, we do not support dynamic loading of select options. If you were to update options (for example after API call) then you would have to `dispose` the select instance and then `initialize` the component again.

Our next release is going to include a new Autocomplete component that I think would be more fitting to achieve what you need. The component is finished and is waiting for the release. You can check how it's going to work here:
https://mdbootstrap.com/docs/standard/forms/autocomplete/#section-async-search
