### ISSUE TITLE
Multiple Select: request to add classes for selectAll option

### ISSUE THREAD

**Issue by Nurai1** [mdbootstrap/TW-Elements#2098]
**Describe the bug**
Right now there is no classes attribute to add classes to selectAll option. 

**Expected behavior**
I want something like `data-te-class-select-option-select-all` attribute

**Comment by juujisai** [comment]
Hi, thanks for sending the request. We will try to add this for the next release.

You mean data attribute for adding class for the whole option not the checkbox right?

**Comment by Nurai1** [comment]
@juujisai To the whole option, right
