### ISSUE TITLE
Docs - Datepicker / Timepicker / Infinite scroll - remove double inits from snippets and check options formatting in snippet

### ISSUE THREAD

**Issue by juujisai** [mdbootstrap/TW-Elements#2138]

**Comment by iprzybysz** [comment]
Issue also was found in:

- **Content & Styles:** Animations,

- **Components:** Chips, Popconfirm, Rating,

- **Forms:** Datetimepicker, Range, Validation,

- **Data:** Charts, Charts advanced, Datatables,

- **Methods:** Loading Management, Scrollbar, Touch.
