### ISSUE TITLE
Datatable: setting data-te-entries-options via HTML-attribute results in error

### ISSUE THREAD

**Issue by SergejGleithmann** [mdbootstrap/TW-Elements#2229]
**Describe the bug**
Setting the `entriesOptions`-property via `data-te-entries-options="[...]"` in html results in 
`Uncaught Error: DATATABLE: Option "entriesOptions" provided type "string" but expected type "array".`

**To Reproduce**
Use this:
```html
<div data-te-datatable-init
         data-te-entries-options="[10,20,50,'All']"
         >
</div>
```

It looks to me like the parser for interpreting the HTML-attributes does not support arrays and can only interpret booleans, numbers and strings, ~~however I did not find the code where this happens, so I could not fix it myself~~. I think I found it.

**Comment by SergejGleithmann** [comment]
I guess the error happens somewhere around here: https://github.com/mdbootstrap/TW-Elements/blob/026a359b473152cc1441d1d5e20e69b60ae348c7/src/js/dom/manipulator.js#L14C7-L14C7

I would maybe use something like this: 
```js
if (type === "array") {
    return JSON.parse(val);
  }
```
However this would require the `type` parameter, that is referenced in the `index.js` of the components. The way it is now, it prevents certain attributes. For example one can not set an attribute to a string that only consists of numbers even if the attribute expects a string. Also "false" is always interpreted as a boolean even if the attribute expects a string. This could then be refactored as well.
Would this be appreciated?

**Comment by juujisai** [comment]
Hi! You are rignt, adding Objects and Arrays inside data attributes does not work at this moment. The best way to set options that contains those two is to do it via JS. We are going to discuss this in our team and decide whether this should be changed.

As of the attributes that consists of numbers or booleans I think it works as it should. Those values should be considered either as a number or as a boolean - if the string inside the data attribute says `false` then it should be considered as a boolean value.

Do you have any example where that could create an issue? Maybe I'm missing something.

**Comment by SergejGleithmann** [comment]
@juujisai Hello, thank you for the answer. No I have not yet encountered an instance of this causing problems. I just stumbled upon this when I was trying to understand my error. Maybe the most realistic issue would be if you would enter a number but expect it to be read as a string, then this might lead to issues.

I would be ok with closing this issue unless you want to change the behaviour of parsing - you mentioned that you want to discuss it in your team.

Best Regards
Serj

**Comment by juujisai** [comment]
Hi @SergejGleithmann , for now arrays in options in most cases will have to provided via JS. Adding support for putting arrays directly in data attributes might be a bit tricky for now, but we're keeping an eye on it. 

We're going to making it possible to use arrays for the `entriesOptions` option in the future though.
