### ISSUE TITLE
Checkbox/Radiobutton: hard typed coloring

### ISSUE THREAD

**Issue by SergejGleithmann** [mdbootstrap/TW-Elements#2230]
The default checkbox has the class `checked:focus:before:shadow-[0px_0px_0px_13px_#3b71ca]` (and also a version for `dark:`-prefix). I feel this is suboptimal, because imo coloring should be tied to primary, secondary etc. My design features a red primary color and `#3b71ca` simply does not fit this scheme.

I am able adapt this in my html by ommiting this class, however if I use datatables with the selectable attribute, they use the default checkbox. Now I would have to manipulate the checkboxes of the datatable by hand and this feels not like this should be the case.

I anticipate that there is no good way of using shadows with tailwind colors and this is the reason for this implementation, but maybe there is a better solution. Would this be a reasonable change?

**Comment by juujisai** [comment]
We are planning to extend the tailwind shadow classes (and other arbitrary classes that are used multiple times) with shadows that we are using the most in our components. We'll try to to make it work with primary colors.

At this moment you can update this class inside your project by yourself:

This class: `shadow-[0px_0px_0px_13px_#3b71ca]` 
Should work the same as those two: `shadow-[0px_0px_0px_13px] shadow-primary`

**Comment by SergejGleithmann** [comment]
@juujisai Thaky you for your answer. Can I change this globally because as I said my main problem are the autogenerated elements, that are hard to manipulate in HTML, like for example the ring in the Autocomplete Component.

**Comment by juujisai** [comment]
@SergejGleithmann Unfortunately you can't change this globally right now. You would have to use our class customization to change elements you need.

**Comment by SergejGleithmann** [comment]
@juujisai Alright, thank you for clarification!

Should we close this issue then?

**Comment by iprzybysz** [comment]
Hi @SergejGleithmann, I think the topic has been exhausted and this issue can be closed.
