### ISSUE TITLE
[Angular] - Datepicker re-initialization not wroking

### ISSUE THREAD

**Issue by asllanberishadev** [mdbootstrap/TW-Elements#2322]
Hi there,

I'm using Datepicker into a modal, which is a component. When opening the modal first time, it works just fine, but anytime after that datepicker crashes. So, clicking the input won't trigger the popup datepicker. 
I expect the datepicker popup to work each time modal is opened.

Code: 
Initialization in component: 
ngAfterViewChecked(): void {
    initTE({ Datepicker, Input });
}

In HMTL template I've just copy/pasted the first Basic example from the Datepicker docs. 

- OS: [macOS]
- Browser [chrome]

<img width="362" alt="Screenshot 2024-03-02 at 17 06 03" src="https://github.com/mdbootstrap/TW-Elements/assets/69054286/8972c833-3657-4a4f-be00-58cada13e6f5">
<img width="359" alt="Screenshot 2024-03-02 at 17 06 16" src="https://github.com/mdbootstrap/TW-Elements/assets/69054286/de88c432-0a93-48d2-aecb-8abd74b736eb">

**Comment by iprzybysz** [comment]
Hi @asllanberishadev, check out our [Quick Start](https://tw-elements.com/docs/standard/getting-started/quick-start/) page and [TW Elements Formats](https://tw-elements.com/docs/standard/getting-started/quick-start/#formats) section where you'll find everything about `initTE` method.  This method has an `allowReinits` option, which should fix this issue.

**Comment by asllanberishadev** [comment]
Thanks, fixed!
