### ISSUE TITLE
Registration on Site - registration not taking, pw reset not working

### ISSUE THREAD

**Issue by MacelinCane** [mdbootstrap/TW-Elements#2323]
**Describe the bug**
I've registered on the site so I could purchase a license.
I created a username and used my email address and carefully collected and stored a password that I used to register.

The log in effort yields a "wrong password" error.
The password reset button doesn't function.

**To Reproduce**

1. Go to 'https://tw-elements.com/docs/standard/navigation/breadcrumbs/'
2. Click on 'LOGIN'
3. Choose 'Register'
4. fill out form and click signup
5. Not sure if I should get an email, but I don't.

1. Try to log in
2. Get 'wrong username or password' error
3. try with both established username and established password
4. both fail

1. Try to register again
2. both my email address and username are recognized as taken.

**Expected behavior**
to be able to log in

**Actual behavior**
1. Try to log in
2. Get 'wrong username or password' error
3. try with both established username and established password
4. both fail

**Desktop:**

- OS: [e.g. Win10]
- Browser [Chrome]
- Version [Version 121.0.6167.189]

**Comment by MacelinCane** [comment]
I tried again using a generic gmail address and I was able to gain access to the site and remain logged in. Perhaps membership does not like the [dot]solutions tld of my previous attempt.
I was able to successfully make a purchase of a single user license agreement, but when I try to SEE it, I am taken to a new site [mdbootrap] that says I am not registered there. 
I am unable to log in using the same credentials I created successfully for the twe site.
It's crazy confusing.

So when I try to register using the same username I used on the TWE site, I am blocked from doing that. 
I WAS able to create, I guess, a new account on the mdbootrap site using the **same gmail** address as mentioned above,
Once I got logged in, I clicked on Orders and it said I had not placed any orders...
https://app.screencast.com/NokT3MGREqGEo
Here is a screenshot of my receipt from my credit card company:
https://app.screencast.com/q6tV7BqcjjciH
This is the email I got from mdb
https://app.screencast.com/4MspK4CcZrY4C
this is the redacted receipt I got from StartupFlow. I assume this is your business entity. 
https://app.screencast.com/J4M0C39hXYzxk
if someone want's to direct message me at chrs.purser@gmail.com I can reply with actual numbers.
This is what I got when following stripe's Manage Subscription link in that email
https://app.screencast.com/HNsZYWS1cLYXb
and this is what I see when I click on the link Stripe sent 
https://app.screencast.com/Yxxq7MKW7uLsk
And even after all that, I still am blocked in the sample code area of the twe site
https://app.screencast.com/pdUgobGnA3WKt
And when I click on my logged in icon again on twe and I am taken to mdb where it's clear I AM logged in, this happens
https://app.screencast.com/HOmoD3o0KXQS3
This is a fresh video starting a new incog window and trying again
https://app.screencast.com/ngSY50PaolZtD
Please help. I am consuming lots of time trying to gain access to code examples.

**Comment by juujisai** [comment]
Hi! Everything should work properly now. Let us know if you encounter any more problems!

**Comment by MacelinCane** [comment]
Hi, Thankyou.
Yes, logged in and still locked out.
Even tried relogging in via incognito and got the same.

[image: image.png]

Although I do see the active license here - even though dark mode isn't
looking great yet. (we all suffer that haha)
[image: image.png]
And this is working now
https://mdbootstrap.com/profile/my-orders/
[image: image.png]

The part I really need is the part not working lol.
Access to example code...

Thanks!

*CHRIS PURSER*
954-610-3659
*This email with contents and attachments is confidential. The maintenance
of trust should be considered before sharing.*

**Comment by juujisai** [comment]
You can't open the snippets with code right? Did you try to run the `ctrl+shift+r` ?

**Comment by MacelinCane** [comment]
Correct. I cannot open the code snippets.
I didn't just try hard refreshing, I tried a fully fresh incognito session.
no luck...
Thanks

*CHRIS PURSER*
954-610-3659
*This email with contents and attachments is confidential. The maintenance
of trust should be considered before sharing.*

**Comment by MacelinCane** [comment]
here's a video that might help
https://app.screencast.com/g63eS8LuU1rbL

*CHRIS PURSER*
954-610-3659
*This email with contents and attachments is confidential. The maintenance
of trust should be considered before sharing.*

**Comment by catchmareck** [comment]
Hey @MacelinCane , I've emailed you at the mail address you shared above ;)

**Comment by MacelinCane** [comment]
All good now. Thank you!
