### ISSUE TITLE
v2.0 missing components

### ISSUE THREAD

**Issue by jamesRUS52** [mdbootstrap/TW-Elements#2327]
Why are you moving free commponents from v1 to PRO subscription in v2 f.g. sidebar and datepicker ??? 
It's full shit and is not right way. You should add new components to new version and PRO subscription/
I will not update to new version. And How can I read docs for v.1  ???

**Comment by juujisai** [comment]
To access the v1.0.0 docs you have to open them locally. You can find the guide here: https://tw-elements.com/docs/standard/getting-started/local-installation/

You will need hugo for that (I recommend hugo v0.106.0 version)

**Comment by Thunraz** [comment]
While I value your work and understand you need to monetize it, it's quite unfriendly to users to hide documentation for the old version behind "install it yourself" requiring a specific version of a third party tool. Since you're already using a static site generator, it wouldn't be the hardest thing to host a legacy documentation.
For me, it doesn't cast the best light on your project unfortunately.

**Comment by jamesRUS52** [comment]
I will migrate to another framework/components.
It's very unfriendly and uncomfortable here right now. Even the basic select element has become paid. This is too much

**Comment by filipkappa** [comment]
@jamesRUS52 @Thunraz 

Just to be clear - **everything that was released as open source in TWE is still available for free**.

We are leaving everything from the previous versions of TWE untouched. Everything that was already published under AGPL will stay under AGPL, that includes:
- all components
- all tutorials
- full documentation

**Everything we released so far will stay open source, and is still fully functional & reliable tool under AGPL.**
You can access all versions with their documentation on the same repository **[under a specific release tag](https://github.com/mdbootstrap/TW-Elements/releases/)**.

You can still download the package & **[run the documentation locally](https://tw-elements.com/docs/standard/getting-started/local-installation/)**.

You can learn more about the whole process we went trough with this change here:
https://github.com/mdbootstrap/TW-Elements/discussions/2326
